// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbExchangeQuoteMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pbExchangeQuoteMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace ExchangeQuoteMessage {

void protobuf_ShutdownFile_pbExchangeQuoteMessage_2eproto() {
  delete BaseQuoteRsp::default_instance_;
  delete OptionQuoteRsp::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_pbExchangeQuoteMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_pbExchangeQuoteMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  BaseQuoteRsp::default_instance_ = new BaseQuoteRsp();
  OptionQuoteRsp::default_instance_ = new OptionQuoteRsp();
  BaseQuoteRsp::default_instance_->InitAsDefaultInstance();
  OptionQuoteRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pbExchangeQuoteMessage_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_once_);
void protobuf_AddDesc_pbExchangeQuoteMessage_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_once_,
                 &protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pbExchangeQuoteMessage_2eproto {
  StaticDescriptorInitializer_pbExchangeQuoteMessage_2eproto() {
    protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
  }
} static_descriptor_initializer_pbExchangeQuoteMessage_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BaseQuoteRsp::kStrTradeDateFieldNumber;
const int BaseQuoteRsp::kStrExchangeFieldNumber;
const int BaseQuoteRsp::kStrComodityFieldNumber;
const int BaseQuoteRsp::kStrContractNoFieldNumber;
const int BaseQuoteRsp::kStrDateTimeStampFieldNumber;
const int BaseQuoteRsp::kStrMiliSecFieldNumber;
const int BaseQuoteRsp::kDQPreClosingPriceFieldNumber;
const int BaseQuoteRsp::kDQPreSettlePriceFieldNumber;
const int BaseQuoteRsp::kI64QPrePositionQtyFieldNumber;
const int BaseQuoteRsp::kDQOpeningPriceFieldNumber;
const int BaseQuoteRsp::kDQLastPriceFieldNumber;
const int BaseQuoteRsp::kDQHighPriceFieldNumber;
const int BaseQuoteRsp::kDQLowPriceFieldNumber;
const int BaseQuoteRsp::kDQLimitUpPriceFieldNumber;
const int BaseQuoteRsp::kDQLimitDownPriceFieldNumber;
const int BaseQuoteRsp::kI64QTotalQtyFieldNumber;
const int BaseQuoteRsp::kI64QPositionQtyFieldNumber;
const int BaseQuoteRsp::kDQClosingPriceFieldNumber;
const int BaseQuoteRsp::kQSettlePriceFieldNumber;
const int BaseQuoteRsp::kI64QLastQtyFieldNumber;
const int BaseQuoteRsp::kDQBidPrice1FieldNumber;
const int BaseQuoteRsp::kDQBidPrice2FieldNumber;
const int BaseQuoteRsp::kDQBidPrice3FieldNumber;
const int BaseQuoteRsp::kDQBidPrice4FieldNumber;
const int BaseQuoteRsp::kDQBidPrice5FieldNumber;
const int BaseQuoteRsp::kI64QBidQty1FieldNumber;
const int BaseQuoteRsp::kI64QBidQty2FieldNumber;
const int BaseQuoteRsp::kI64QBidQty3FieldNumber;
const int BaseQuoteRsp::kI64QBidQty4FieldNumber;
const int BaseQuoteRsp::kI64QBidQty5FieldNumber;
const int BaseQuoteRsp::kDQAskPrice1FieldNumber;
const int BaseQuoteRsp::kDQAskPrice2FieldNumber;
const int BaseQuoteRsp::kDQAskPrice3FieldNumber;
const int BaseQuoteRsp::kDQAskPrice4FieldNumber;
const int BaseQuoteRsp::kDQAskPrice5FieldNumber;
const int BaseQuoteRsp::kI64QAskQty1FieldNumber;
const int BaseQuoteRsp::kI64QAskQty2FieldNumber;
const int BaseQuoteRsp::kI64QAskQty3FieldNumber;
const int BaseQuoteRsp::kI64QAskQty4FieldNumber;
const int BaseQuoteRsp::kI64QAskQty5FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BaseQuoteRsp::BaseQuoteRsp()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ExchangeQuoteMessage.BaseQuoteRsp)
}

void BaseQuoteRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

BaseQuoteRsp::BaseQuoteRsp(const BaseQuoteRsp& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ExchangeQuoteMessage.BaseQuoteRsp)
}

void BaseQuoteRsp::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  strtradedate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strexchange_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodity_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdatetimestamp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strmilisec_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dqpreclosingprice_ = 0;
  dqpresettleprice_ = 0;
  i64qprepositionqty_ = GOOGLE_ULONGLONG(0);
  dqopeningprice_ = 0;
  dqlastprice_ = 0;
  dqhighprice_ = 0;
  dqlowprice_ = 0;
  dqlimitupprice_ = 0;
  dqlimitdownprice_ = 0;
  i64qtotalqty_ = GOOGLE_ULONGLONG(0);
  i64qpositionqty_ = GOOGLE_ULONGLONG(0);
  dqclosingprice_ = 0;
  qsettleprice_ = 0;
  i64qlastqty_ = GOOGLE_ULONGLONG(0);
  dqbidprice1_ = 0;
  dqbidprice2_ = 0;
  dqbidprice3_ = 0;
  dqbidprice4_ = 0;
  dqbidprice5_ = 0;
  i64qbidqty1_ = GOOGLE_ULONGLONG(0);
  i64qbidqty2_ = GOOGLE_ULONGLONG(0);
  i64qbidqty3_ = GOOGLE_ULONGLONG(0);
  i64qbidqty4_ = GOOGLE_ULONGLONG(0);
  i64qbidqty5_ = GOOGLE_ULONGLONG(0);
  dqaskprice1_ = 0;
  dqaskprice2_ = 0;
  dqaskprice3_ = 0;
  dqaskprice4_ = 0;
  dqaskprice5_ = 0;
  i64qaskqty1_ = GOOGLE_ULONGLONG(0);
  i64qaskqty2_ = GOOGLE_ULONGLONG(0);
  i64qaskqty3_ = GOOGLE_ULONGLONG(0);
  i64qaskqty4_ = GOOGLE_ULONGLONG(0);
  i64qaskqty5_ = GOOGLE_ULONGLONG(0);
}

BaseQuoteRsp::~BaseQuoteRsp() {
  // @@protoc_insertion_point(destructor:ExchangeQuoteMessage.BaseQuoteRsp)
  SharedDtor();
}

void BaseQuoteRsp::SharedDtor() {
  strtradedate_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strexchange_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodity_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdatetimestamp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strmilisec_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void BaseQuoteRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BaseQuoteRsp& BaseQuoteRsp::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
#endif
  return *default_instance_;
}

BaseQuoteRsp* BaseQuoteRsp::default_instance_ = NULL;

BaseQuoteRsp* BaseQuoteRsp::New(::google::protobuf::Arena* arena) const {
  BaseQuoteRsp* n = new BaseQuoteRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BaseQuoteRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:ExchangeQuoteMessage.BaseQuoteRsp)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(BaseQuoteRsp, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<BaseQuoteRsp*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(dqpreclosingprice_, dqpresettleprice_);
  strtradedate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodity_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdatetimestamp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strmilisec_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ZR_(i64qprepositionqty_, i64qtotalqty_);
  ZR_(i64qpositionqty_, dqbidprice4_);
  ZR_(dqbidprice5_, dqaskprice2_);
  ZR_(dqaskprice3_, i64qaskqty5_);

#undef ZR_HELPER_
#undef ZR_

}

bool BaseQuoteRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ExchangeQuoteMessage.BaseQuoteRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes strTradeDate = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strtradedate()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_strExchange;
        break;
      }

      // optional bytes strExchange = 2;
      case 2: {
        if (tag == 18) {
         parse_strExchange:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strexchange()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_strComodity;
        break;
      }

      // optional bytes strComodity = 3;
      case 3: {
        if (tag == 26) {
         parse_strComodity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcomodity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_strContractNo;
        break;
      }

      // optional bytes strContractNo = 4;
      case 4: {
        if (tag == 34) {
         parse_strContractNo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcontractno()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_strDateTimeStamp;
        break;
      }

      // optional bytes strDateTimeStamp = 5;
      case 5: {
        if (tag == 42) {
         parse_strDateTimeStamp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strdatetimestamp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_strMiliSec;
        break;
      }

      // optional bytes strMiliSec = 6;
      case 6: {
        if (tag == 50) {
         parse_strMiliSec:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strmilisec()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_dQPreClosingPrice;
        break;
      }

      // optional double dQPreClosingPrice = 7;
      case 7: {
        if (tag == 57) {
         parse_dQPreClosingPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqpreclosingprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_dQPreSettlePrice;
        break;
      }

      // optional double dQPreSettlePrice = 8;
      case 8: {
        if (tag == 65) {
         parse_dQPreSettlePrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqpresettleprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_i64QPrePositionQty;
        break;
      }

      // optional uint64 i64QPrePositionQty = 9;
      case 9: {
        if (tag == 72) {
         parse_i64QPrePositionQty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qprepositionqty_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_dQOpeningPrice;
        break;
      }

      // optional double dQOpeningPrice = 10;
      case 10: {
        if (tag == 81) {
         parse_dQOpeningPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqopeningprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(89)) goto parse_dQLastPrice;
        break;
      }

      // optional double dQLastPrice = 11;
      case 11: {
        if (tag == 89) {
         parse_dQLastPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqlastprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(97)) goto parse_dQHighPrice;
        break;
      }

      // optional double dQHighPrice = 12;
      case 12: {
        if (tag == 97) {
         parse_dQHighPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqhighprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(105)) goto parse_dQLowPrice;
        break;
      }

      // optional double dQLowPrice = 13;
      case 13: {
        if (tag == 105) {
         parse_dQLowPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqlowprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(113)) goto parse_dQLimitUpPrice;
        break;
      }

      // optional double dQLimitUpPrice = 14;
      case 14: {
        if (tag == 113) {
         parse_dQLimitUpPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqlimitupprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(121)) goto parse_dQLimitDownPrice;
        break;
      }

      // optional double dQLimitDownPrice = 15;
      case 15: {
        if (tag == 121) {
         parse_dQLimitDownPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqlimitdownprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_i64QTotalQty;
        break;
      }

      // optional uint64 i64QTotalQty = 16;
      case 16: {
        if (tag == 128) {
         parse_i64QTotalQty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qtotalqty_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(136)) goto parse_i64QPositionQty;
        break;
      }

      // optional uint64 i64QPositionQty = 17;
      case 17: {
        if (tag == 136) {
         parse_i64QPositionQty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qpositionqty_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(145)) goto parse_dQClosingPrice;
        break;
      }

      // optional double dQClosingPrice = 18;
      case 18: {
        if (tag == 145) {
         parse_dQClosingPrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqclosingprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(153)) goto parse_QSettlePrice;
        break;
      }

      // optional double QSettlePrice = 19;
      case 19: {
        if (tag == 153) {
         parse_QSettlePrice:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &qsettleprice_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(160)) goto parse_i64QLastQty;
        break;
      }

      // optional uint64 i64QLastQty = 20;
      case 20: {
        if (tag == 160) {
         parse_i64QLastQty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qlastqty_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(169)) goto parse_dQBidPrice1;
        break;
      }

      // optional double dQBidPrice1 = 21;
      case 21: {
        if (tag == 169) {
         parse_dQBidPrice1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqbidprice1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(177)) goto parse_dQBidPrice2;
        break;
      }

      // optional double dQBidPrice2 = 22;
      case 22: {
        if (tag == 177) {
         parse_dQBidPrice2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqbidprice2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(185)) goto parse_dQBidPrice3;
        break;
      }

      // optional double dQBidPrice3 = 23;
      case 23: {
        if (tag == 185) {
         parse_dQBidPrice3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqbidprice3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(193)) goto parse_dQBidPrice4;
        break;
      }

      // optional double dQBidPrice4 = 24;
      case 24: {
        if (tag == 193) {
         parse_dQBidPrice4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqbidprice4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(201)) goto parse_dQBidPrice5;
        break;
      }

      // optional double dQBidPrice5 = 25;
      case 25: {
        if (tag == 201) {
         parse_dQBidPrice5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqbidprice5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(208)) goto parse_i64QBidQty1;
        break;
      }

      // optional uint64 i64QBidQty1 = 26;
      case 26: {
        if (tag == 208) {
         parse_i64QBidQty1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qbidqty1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(216)) goto parse_i64QBidQty2;
        break;
      }

      // optional uint64 i64QBidQty2 = 27;
      case 27: {
        if (tag == 216) {
         parse_i64QBidQty2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qbidqty2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(224)) goto parse_i64QBidQty3;
        break;
      }

      // optional uint64 i64QBidQty3 = 28;
      case 28: {
        if (tag == 224) {
         parse_i64QBidQty3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qbidqty3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(232)) goto parse_i64QBidQty4;
        break;
      }

      // optional uint64 i64QBidQty4 = 29;
      case 29: {
        if (tag == 232) {
         parse_i64QBidQty4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qbidqty4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(240)) goto parse_i64QBidQty5;
        break;
      }

      // optional uint64 i64QBidQty5 = 30;
      case 30: {
        if (tag == 240) {
         parse_i64QBidQty5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qbidqty5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(249)) goto parse_dQAskPrice1;
        break;
      }

      // optional double dQAskPrice1 = 31;
      case 31: {
        if (tag == 249) {
         parse_dQAskPrice1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqaskprice1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(257)) goto parse_dQAskPrice2;
        break;
      }

      // optional double dQAskPrice2 = 32;
      case 32: {
        if (tag == 257) {
         parse_dQAskPrice2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqaskprice2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(265)) goto parse_dQAskPrice3;
        break;
      }

      // optional double dQAskPrice3 = 33;
      case 33: {
        if (tag == 265) {
         parse_dQAskPrice3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqaskprice3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(273)) goto parse_dQAskPrice4;
        break;
      }

      // optional double dQAskPrice4 = 34;
      case 34: {
        if (tag == 273) {
         parse_dQAskPrice4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqaskprice4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(281)) goto parse_dQAskPrice5;
        break;
      }

      // optional double dQAskPrice5 = 35;
      case 35: {
        if (tag == 281) {
         parse_dQAskPrice5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dqaskprice5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(288)) goto parse_i64QAskQty1;
        break;
      }

      // optional uint64 i64QAskQty1 = 36;
      case 36: {
        if (tag == 288) {
         parse_i64QAskQty1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qaskqty1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(296)) goto parse_i64QAskQty2;
        break;
      }

      // optional uint64 i64QAskQty2 = 37;
      case 37: {
        if (tag == 296) {
         parse_i64QAskQty2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qaskqty2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(304)) goto parse_i64QAskQty3;
        break;
      }

      // optional uint64 i64QAskQty3 = 38;
      case 38: {
        if (tag == 304) {
         parse_i64QAskQty3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qaskqty3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(312)) goto parse_i64QAskQty4;
        break;
      }

      // optional uint64 i64QAskQty4 = 39;
      case 39: {
        if (tag == 312) {
         parse_i64QAskQty4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qaskqty4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(320)) goto parse_i64QAskQty5;
        break;
      }

      // optional uint64 i64QAskQty5 = 40;
      case 40: {
        if (tag == 320) {
         parse_i64QAskQty5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64qaskqty5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ExchangeQuoteMessage.BaseQuoteRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ExchangeQuoteMessage.BaseQuoteRsp)
  return false;
#undef DO_
}

void BaseQuoteRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ExchangeQuoteMessage.BaseQuoteRsp)
  // optional bytes strTradeDate = 1;
  if (this->strtradedate().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->strtradedate(), output);
  }

  // optional bytes strExchange = 2;
  if (this->strexchange().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->strexchange(), output);
  }

  // optional bytes strComodity = 3;
  if (this->strcomodity().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->strcomodity(), output);
  }

  // optional bytes strContractNo = 4;
  if (this->strcontractno().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->strcontractno(), output);
  }

  // optional bytes strDateTimeStamp = 5;
  if (this->strdatetimestamp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->strdatetimestamp(), output);
  }

  // optional bytes strMiliSec = 6;
  if (this->strmilisec().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->strmilisec(), output);
  }

  // optional double dQPreClosingPrice = 7;
  if (this->dqpreclosingprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->dqpreclosingprice(), output);
  }

  // optional double dQPreSettlePrice = 8;
  if (this->dqpresettleprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->dqpresettleprice(), output);
  }

  // optional uint64 i64QPrePositionQty = 9;
  if (this->i64qprepositionqty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(9, this->i64qprepositionqty(), output);
  }

  // optional double dQOpeningPrice = 10;
  if (this->dqopeningprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->dqopeningprice(), output);
  }

  // optional double dQLastPrice = 11;
  if (this->dqlastprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->dqlastprice(), output);
  }

  // optional double dQHighPrice = 12;
  if (this->dqhighprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->dqhighprice(), output);
  }

  // optional double dQLowPrice = 13;
  if (this->dqlowprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->dqlowprice(), output);
  }

  // optional double dQLimitUpPrice = 14;
  if (this->dqlimitupprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(14, this->dqlimitupprice(), output);
  }

  // optional double dQLimitDownPrice = 15;
  if (this->dqlimitdownprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(15, this->dqlimitdownprice(), output);
  }

  // optional uint64 i64QTotalQty = 16;
  if (this->i64qtotalqty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(16, this->i64qtotalqty(), output);
  }

  // optional uint64 i64QPositionQty = 17;
  if (this->i64qpositionqty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(17, this->i64qpositionqty(), output);
  }

  // optional double dQClosingPrice = 18;
  if (this->dqclosingprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(18, this->dqclosingprice(), output);
  }

  // optional double QSettlePrice = 19;
  if (this->qsettleprice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(19, this->qsettleprice(), output);
  }

  // optional uint64 i64QLastQty = 20;
  if (this->i64qlastqty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(20, this->i64qlastqty(), output);
  }

  // optional double dQBidPrice1 = 21;
  if (this->dqbidprice1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(21, this->dqbidprice1(), output);
  }

  // optional double dQBidPrice2 = 22;
  if (this->dqbidprice2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(22, this->dqbidprice2(), output);
  }

  // optional double dQBidPrice3 = 23;
  if (this->dqbidprice3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(23, this->dqbidprice3(), output);
  }

  // optional double dQBidPrice4 = 24;
  if (this->dqbidprice4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(24, this->dqbidprice4(), output);
  }

  // optional double dQBidPrice5 = 25;
  if (this->dqbidprice5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(25, this->dqbidprice5(), output);
  }

  // optional uint64 i64QBidQty1 = 26;
  if (this->i64qbidqty1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(26, this->i64qbidqty1(), output);
  }

  // optional uint64 i64QBidQty2 = 27;
  if (this->i64qbidqty2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(27, this->i64qbidqty2(), output);
  }

  // optional uint64 i64QBidQty3 = 28;
  if (this->i64qbidqty3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(28, this->i64qbidqty3(), output);
  }

  // optional uint64 i64QBidQty4 = 29;
  if (this->i64qbidqty4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(29, this->i64qbidqty4(), output);
  }

  // optional uint64 i64QBidQty5 = 30;
  if (this->i64qbidqty5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(30, this->i64qbidqty5(), output);
  }

  // optional double dQAskPrice1 = 31;
  if (this->dqaskprice1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(31, this->dqaskprice1(), output);
  }

  // optional double dQAskPrice2 = 32;
  if (this->dqaskprice2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(32, this->dqaskprice2(), output);
  }

  // optional double dQAskPrice3 = 33;
  if (this->dqaskprice3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(33, this->dqaskprice3(), output);
  }

  // optional double dQAskPrice4 = 34;
  if (this->dqaskprice4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(34, this->dqaskprice4(), output);
  }

  // optional double dQAskPrice5 = 35;
  if (this->dqaskprice5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(35, this->dqaskprice5(), output);
  }

  // optional uint64 i64QAskQty1 = 36;
  if (this->i64qaskqty1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(36, this->i64qaskqty1(), output);
  }

  // optional uint64 i64QAskQty2 = 37;
  if (this->i64qaskqty2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(37, this->i64qaskqty2(), output);
  }

  // optional uint64 i64QAskQty3 = 38;
  if (this->i64qaskqty3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(38, this->i64qaskqty3(), output);
  }

  // optional uint64 i64QAskQty4 = 39;
  if (this->i64qaskqty4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(39, this->i64qaskqty4(), output);
  }

  // optional uint64 i64QAskQty5 = 40;
  if (this->i64qaskqty5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(40, this->i64qaskqty5(), output);
  }

  // @@protoc_insertion_point(serialize_end:ExchangeQuoteMessage.BaseQuoteRsp)
}

int BaseQuoteRsp::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ExchangeQuoteMessage.BaseQuoteRsp)
  int total_size = 0;

  // optional bytes strTradeDate = 1;
  if (this->strtradedate().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strtradedate());
  }

  // optional bytes strExchange = 2;
  if (this->strexchange().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strexchange());
  }

  // optional bytes strComodity = 3;
  if (this->strcomodity().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcomodity());
  }

  // optional bytes strContractNo = 4;
  if (this->strcontractno().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcontractno());
  }

  // optional bytes strDateTimeStamp = 5;
  if (this->strdatetimestamp().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strdatetimestamp());
  }

  // optional bytes strMiliSec = 6;
  if (this->strmilisec().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strmilisec());
  }

  // optional double dQPreClosingPrice = 7;
  if (this->dqpreclosingprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQPreSettlePrice = 8;
  if (this->dqpresettleprice() != 0) {
    total_size += 1 + 8;
  }

  // optional uint64 i64QPrePositionQty = 9;
  if (this->i64qprepositionqty() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qprepositionqty());
  }

  // optional double dQOpeningPrice = 10;
  if (this->dqopeningprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQLastPrice = 11;
  if (this->dqlastprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQHighPrice = 12;
  if (this->dqhighprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQLowPrice = 13;
  if (this->dqlowprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQLimitUpPrice = 14;
  if (this->dqlimitupprice() != 0) {
    total_size += 1 + 8;
  }

  // optional double dQLimitDownPrice = 15;
  if (this->dqlimitdownprice() != 0) {
    total_size += 1 + 8;
  }

  // optional uint64 i64QTotalQty = 16;
  if (this->i64qtotalqty() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qtotalqty());
  }

  // optional uint64 i64QPositionQty = 17;
  if (this->i64qpositionqty() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qpositionqty());
  }

  // optional double dQClosingPrice = 18;
  if (this->dqclosingprice() != 0) {
    total_size += 2 + 8;
  }

  // optional double QSettlePrice = 19;
  if (this->qsettleprice() != 0) {
    total_size += 2 + 8;
  }

  // optional uint64 i64QLastQty = 20;
  if (this->i64qlastqty() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qlastqty());
  }

  // optional double dQBidPrice1 = 21;
  if (this->dqbidprice1() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQBidPrice2 = 22;
  if (this->dqbidprice2() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQBidPrice3 = 23;
  if (this->dqbidprice3() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQBidPrice4 = 24;
  if (this->dqbidprice4() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQBidPrice5 = 25;
  if (this->dqbidprice5() != 0) {
    total_size += 2 + 8;
  }

  // optional uint64 i64QBidQty1 = 26;
  if (this->i64qbidqty1() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qbidqty1());
  }

  // optional uint64 i64QBidQty2 = 27;
  if (this->i64qbidqty2() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qbidqty2());
  }

  // optional uint64 i64QBidQty3 = 28;
  if (this->i64qbidqty3() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qbidqty3());
  }

  // optional uint64 i64QBidQty4 = 29;
  if (this->i64qbidqty4() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qbidqty4());
  }

  // optional uint64 i64QBidQty5 = 30;
  if (this->i64qbidqty5() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qbidqty5());
  }

  // optional double dQAskPrice1 = 31;
  if (this->dqaskprice1() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQAskPrice2 = 32;
  if (this->dqaskprice2() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQAskPrice3 = 33;
  if (this->dqaskprice3() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQAskPrice4 = 34;
  if (this->dqaskprice4() != 0) {
    total_size += 2 + 8;
  }

  // optional double dQAskPrice5 = 35;
  if (this->dqaskprice5() != 0) {
    total_size += 2 + 8;
  }

  // optional uint64 i64QAskQty1 = 36;
  if (this->i64qaskqty1() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qaskqty1());
  }

  // optional uint64 i64QAskQty2 = 37;
  if (this->i64qaskqty2() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qaskqty2());
  }

  // optional uint64 i64QAskQty3 = 38;
  if (this->i64qaskqty3() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qaskqty3());
  }

  // optional uint64 i64QAskQty4 = 39;
  if (this->i64qaskqty4() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qaskqty4());
  }

  // optional uint64 i64QAskQty5 = 40;
  if (this->i64qaskqty5() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64qaskqty5());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BaseQuoteRsp::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BaseQuoteRsp*>(&from));
}

void BaseQuoteRsp::MergeFrom(const BaseQuoteRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ExchangeQuoteMessage.BaseQuoteRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.strtradedate().size() > 0) {

    strtradedate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strtradedate_);
  }
  if (from.strexchange().size() > 0) {

    strexchange_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strexchange_);
  }
  if (from.strcomodity().size() > 0) {

    strcomodity_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcomodity_);
  }
  if (from.strcontractno().size() > 0) {

    strcontractno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcontractno_);
  }
  if (from.strdatetimestamp().size() > 0) {

    strdatetimestamp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdatetimestamp_);
  }
  if (from.strmilisec().size() > 0) {

    strmilisec_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strmilisec_);
  }
  if (from.dqpreclosingprice() != 0) {
    set_dqpreclosingprice(from.dqpreclosingprice());
  }
  if (from.dqpresettleprice() != 0) {
    set_dqpresettleprice(from.dqpresettleprice());
  }
  if (from.i64qprepositionqty() != 0) {
    set_i64qprepositionqty(from.i64qprepositionqty());
  }
  if (from.dqopeningprice() != 0) {
    set_dqopeningprice(from.dqopeningprice());
  }
  if (from.dqlastprice() != 0) {
    set_dqlastprice(from.dqlastprice());
  }
  if (from.dqhighprice() != 0) {
    set_dqhighprice(from.dqhighprice());
  }
  if (from.dqlowprice() != 0) {
    set_dqlowprice(from.dqlowprice());
  }
  if (from.dqlimitupprice() != 0) {
    set_dqlimitupprice(from.dqlimitupprice());
  }
  if (from.dqlimitdownprice() != 0) {
    set_dqlimitdownprice(from.dqlimitdownprice());
  }
  if (from.i64qtotalqty() != 0) {
    set_i64qtotalqty(from.i64qtotalqty());
  }
  if (from.i64qpositionqty() != 0) {
    set_i64qpositionqty(from.i64qpositionqty());
  }
  if (from.dqclosingprice() != 0) {
    set_dqclosingprice(from.dqclosingprice());
  }
  if (from.qsettleprice() != 0) {
    set_qsettleprice(from.qsettleprice());
  }
  if (from.i64qlastqty() != 0) {
    set_i64qlastqty(from.i64qlastqty());
  }
  if (from.dqbidprice1() != 0) {
    set_dqbidprice1(from.dqbidprice1());
  }
  if (from.dqbidprice2() != 0) {
    set_dqbidprice2(from.dqbidprice2());
  }
  if (from.dqbidprice3() != 0) {
    set_dqbidprice3(from.dqbidprice3());
  }
  if (from.dqbidprice4() != 0) {
    set_dqbidprice4(from.dqbidprice4());
  }
  if (from.dqbidprice5() != 0) {
    set_dqbidprice5(from.dqbidprice5());
  }
  if (from.i64qbidqty1() != 0) {
    set_i64qbidqty1(from.i64qbidqty1());
  }
  if (from.i64qbidqty2() != 0) {
    set_i64qbidqty2(from.i64qbidqty2());
  }
  if (from.i64qbidqty3() != 0) {
    set_i64qbidqty3(from.i64qbidqty3());
  }
  if (from.i64qbidqty4() != 0) {
    set_i64qbidqty4(from.i64qbidqty4());
  }
  if (from.i64qbidqty5() != 0) {
    set_i64qbidqty5(from.i64qbidqty5());
  }
  if (from.dqaskprice1() != 0) {
    set_dqaskprice1(from.dqaskprice1());
  }
  if (from.dqaskprice2() != 0) {
    set_dqaskprice2(from.dqaskprice2());
  }
  if (from.dqaskprice3() != 0) {
    set_dqaskprice3(from.dqaskprice3());
  }
  if (from.dqaskprice4() != 0) {
    set_dqaskprice4(from.dqaskprice4());
  }
  if (from.dqaskprice5() != 0) {
    set_dqaskprice5(from.dqaskprice5());
  }
  if (from.i64qaskqty1() != 0) {
    set_i64qaskqty1(from.i64qaskqty1());
  }
  if (from.i64qaskqty2() != 0) {
    set_i64qaskqty2(from.i64qaskqty2());
  }
  if (from.i64qaskqty3() != 0) {
    set_i64qaskqty3(from.i64qaskqty3());
  }
  if (from.i64qaskqty4() != 0) {
    set_i64qaskqty4(from.i64qaskqty4());
  }
  if (from.i64qaskqty5() != 0) {
    set_i64qaskqty5(from.i64qaskqty5());
  }
}

void BaseQuoteRsp::CopyFrom(const BaseQuoteRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExchangeQuoteMessage.BaseQuoteRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseQuoteRsp::IsInitialized() const {

  return true;
}

void BaseQuoteRsp::Swap(BaseQuoteRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BaseQuoteRsp::InternalSwap(BaseQuoteRsp* other) {
  strtradedate_.Swap(&other->strtradedate_);
  strexchange_.Swap(&other->strexchange_);
  strcomodity_.Swap(&other->strcomodity_);
  strcontractno_.Swap(&other->strcontractno_);
  strdatetimestamp_.Swap(&other->strdatetimestamp_);
  strmilisec_.Swap(&other->strmilisec_);
  std::swap(dqpreclosingprice_, other->dqpreclosingprice_);
  std::swap(dqpresettleprice_, other->dqpresettleprice_);
  std::swap(i64qprepositionqty_, other->i64qprepositionqty_);
  std::swap(dqopeningprice_, other->dqopeningprice_);
  std::swap(dqlastprice_, other->dqlastprice_);
  std::swap(dqhighprice_, other->dqhighprice_);
  std::swap(dqlowprice_, other->dqlowprice_);
  std::swap(dqlimitupprice_, other->dqlimitupprice_);
  std::swap(dqlimitdownprice_, other->dqlimitdownprice_);
  std::swap(i64qtotalqty_, other->i64qtotalqty_);
  std::swap(i64qpositionqty_, other->i64qpositionqty_);
  std::swap(dqclosingprice_, other->dqclosingprice_);
  std::swap(qsettleprice_, other->qsettleprice_);
  std::swap(i64qlastqty_, other->i64qlastqty_);
  std::swap(dqbidprice1_, other->dqbidprice1_);
  std::swap(dqbidprice2_, other->dqbidprice2_);
  std::swap(dqbidprice3_, other->dqbidprice3_);
  std::swap(dqbidprice4_, other->dqbidprice4_);
  std::swap(dqbidprice5_, other->dqbidprice5_);
  std::swap(i64qbidqty1_, other->i64qbidqty1_);
  std::swap(i64qbidqty2_, other->i64qbidqty2_);
  std::swap(i64qbidqty3_, other->i64qbidqty3_);
  std::swap(i64qbidqty4_, other->i64qbidqty4_);
  std::swap(i64qbidqty5_, other->i64qbidqty5_);
  std::swap(dqaskprice1_, other->dqaskprice1_);
  std::swap(dqaskprice2_, other->dqaskprice2_);
  std::swap(dqaskprice3_, other->dqaskprice3_);
  std::swap(dqaskprice4_, other->dqaskprice4_);
  std::swap(dqaskprice5_, other->dqaskprice5_);
  std::swap(i64qaskqty1_, other->i64qaskqty1_);
  std::swap(i64qaskqty2_, other->i64qaskqty2_);
  std::swap(i64qaskqty3_, other->i64qaskqty3_);
  std::swap(i64qaskqty4_, other->i64qaskqty4_);
  std::swap(i64qaskqty5_, other->i64qaskqty5_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string BaseQuoteRsp::GetTypeName() const {
  return "ExchangeQuoteMessage.BaseQuoteRsp";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BaseQuoteRsp

// optional bytes strTradeDate = 1;
void BaseQuoteRsp::clear_strtradedate() {
  strtradedate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strtradedate() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  return strtradedate_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strtradedate(const ::std::string& value) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
 void BaseQuoteRsp::set_strtradedate(const char* value) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
 void BaseQuoteRsp::set_strtradedate(const void* value, size_t size) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
 ::std::string* BaseQuoteRsp::mutable_strtradedate() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  return strtradedate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strtradedate() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  
  return strtradedate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strtradedate(::std::string* strtradedate) {
  if (strtradedate != NULL) {
    
  } else {
    
  }
  strtradedate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strtradedate);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}

// optional bytes strExchange = 2;
void BaseQuoteRsp::clear_strexchange() {
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strexchange() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  return strexchange_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strexchange(const ::std::string& value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
 void BaseQuoteRsp::set_strexchange(const char* value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
 void BaseQuoteRsp::set_strexchange(const void* value, size_t size) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
 ::std::string* BaseQuoteRsp::mutable_strexchange() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  return strexchange_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strexchange() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  
  return strexchange_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strexchange(::std::string* strexchange) {
  if (strexchange != NULL) {
    
  } else {
    
  }
  strexchange_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strexchange);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}

// optional bytes strComodity = 3;
void BaseQuoteRsp::clear_strcomodity() {
  strcomodity_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strcomodity() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  return strcomodity_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strcomodity(const ::std::string& value) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
 void BaseQuoteRsp::set_strcomodity(const char* value) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
 void BaseQuoteRsp::set_strcomodity(const void* value, size_t size) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
 ::std::string* BaseQuoteRsp::mutable_strcomodity() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  return strcomodity_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strcomodity() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  
  return strcomodity_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strcomodity(::std::string* strcomodity) {
  if (strcomodity != NULL) {
    
  } else {
    
  }
  strcomodity_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcomodity);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}

// optional bytes strContractNo = 4;
void BaseQuoteRsp::clear_strcontractno() {
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strcontractno() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  return strcontractno_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strcontractno(const ::std::string& value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
 void BaseQuoteRsp::set_strcontractno(const char* value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
 void BaseQuoteRsp::set_strcontractno(const void* value, size_t size) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
 ::std::string* BaseQuoteRsp::mutable_strcontractno() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  return strcontractno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strcontractno() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  
  return strcontractno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strcontractno(::std::string* strcontractno) {
  if (strcontractno != NULL) {
    
  } else {
    
  }
  strcontractno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcontractno);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}

// optional bytes strDateTimeStamp = 5;
void BaseQuoteRsp::clear_strdatetimestamp() {
  strdatetimestamp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strdatetimestamp() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  return strdatetimestamp_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strdatetimestamp(const ::std::string& value) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
 void BaseQuoteRsp::set_strdatetimestamp(const char* value) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
 void BaseQuoteRsp::set_strdatetimestamp(const void* value, size_t size) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
 ::std::string* BaseQuoteRsp::mutable_strdatetimestamp() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  return strdatetimestamp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strdatetimestamp() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  
  return strdatetimestamp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strdatetimestamp(::std::string* strdatetimestamp) {
  if (strdatetimestamp != NULL) {
    
  } else {
    
  }
  strdatetimestamp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strdatetimestamp);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}

// optional bytes strMiliSec = 6;
void BaseQuoteRsp::clear_strmilisec() {
  strmilisec_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& BaseQuoteRsp::strmilisec() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  return strmilisec_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_strmilisec(const ::std::string& value) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
 void BaseQuoteRsp::set_strmilisec(const char* value) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
 void BaseQuoteRsp::set_strmilisec(const void* value, size_t size) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
 ::std::string* BaseQuoteRsp::mutable_strmilisec() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  return strmilisec_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BaseQuoteRsp::release_strmilisec() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  
  return strmilisec_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BaseQuoteRsp::set_allocated_strmilisec(::std::string* strmilisec) {
  if (strmilisec != NULL) {
    
  } else {
    
  }
  strmilisec_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strmilisec);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}

// optional double dQPreClosingPrice = 7;
void BaseQuoteRsp::clear_dqpreclosingprice() {
  dqpreclosingprice_ = 0;
}
 double BaseQuoteRsp::dqpreclosingprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQPreClosingPrice)
  return dqpreclosingprice_;
}
 void BaseQuoteRsp::set_dqpreclosingprice(double value) {
  
  dqpreclosingprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQPreClosingPrice)
}

// optional double dQPreSettlePrice = 8;
void BaseQuoteRsp::clear_dqpresettleprice() {
  dqpresettleprice_ = 0;
}
 double BaseQuoteRsp::dqpresettleprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQPreSettlePrice)
  return dqpresettleprice_;
}
 void BaseQuoteRsp::set_dqpresettleprice(double value) {
  
  dqpresettleprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQPreSettlePrice)
}

// optional uint64 i64QPrePositionQty = 9;
void BaseQuoteRsp::clear_i64qprepositionqty() {
  i64qprepositionqty_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qprepositionqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QPrePositionQty)
  return i64qprepositionqty_;
}
 void BaseQuoteRsp::set_i64qprepositionqty(::google::protobuf::uint64 value) {
  
  i64qprepositionqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QPrePositionQty)
}

// optional double dQOpeningPrice = 10;
void BaseQuoteRsp::clear_dqopeningprice() {
  dqopeningprice_ = 0;
}
 double BaseQuoteRsp::dqopeningprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQOpeningPrice)
  return dqopeningprice_;
}
 void BaseQuoteRsp::set_dqopeningprice(double value) {
  
  dqopeningprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQOpeningPrice)
}

// optional double dQLastPrice = 11;
void BaseQuoteRsp::clear_dqlastprice() {
  dqlastprice_ = 0;
}
 double BaseQuoteRsp::dqlastprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLastPrice)
  return dqlastprice_;
}
 void BaseQuoteRsp::set_dqlastprice(double value) {
  
  dqlastprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLastPrice)
}

// optional double dQHighPrice = 12;
void BaseQuoteRsp::clear_dqhighprice() {
  dqhighprice_ = 0;
}
 double BaseQuoteRsp::dqhighprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQHighPrice)
  return dqhighprice_;
}
 void BaseQuoteRsp::set_dqhighprice(double value) {
  
  dqhighprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQHighPrice)
}

// optional double dQLowPrice = 13;
void BaseQuoteRsp::clear_dqlowprice() {
  dqlowprice_ = 0;
}
 double BaseQuoteRsp::dqlowprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLowPrice)
  return dqlowprice_;
}
 void BaseQuoteRsp::set_dqlowprice(double value) {
  
  dqlowprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLowPrice)
}

// optional double dQLimitUpPrice = 14;
void BaseQuoteRsp::clear_dqlimitupprice() {
  dqlimitupprice_ = 0;
}
 double BaseQuoteRsp::dqlimitupprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitUpPrice)
  return dqlimitupprice_;
}
 void BaseQuoteRsp::set_dqlimitupprice(double value) {
  
  dqlimitupprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitUpPrice)
}

// optional double dQLimitDownPrice = 15;
void BaseQuoteRsp::clear_dqlimitdownprice() {
  dqlimitdownprice_ = 0;
}
 double BaseQuoteRsp::dqlimitdownprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitDownPrice)
  return dqlimitdownprice_;
}
 void BaseQuoteRsp::set_dqlimitdownprice(double value) {
  
  dqlimitdownprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitDownPrice)
}

// optional uint64 i64QTotalQty = 16;
void BaseQuoteRsp::clear_i64qtotalqty() {
  i64qtotalqty_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qtotalqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QTotalQty)
  return i64qtotalqty_;
}
 void BaseQuoteRsp::set_i64qtotalqty(::google::protobuf::uint64 value) {
  
  i64qtotalqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QTotalQty)
}

// optional uint64 i64QPositionQty = 17;
void BaseQuoteRsp::clear_i64qpositionqty() {
  i64qpositionqty_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qpositionqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QPositionQty)
  return i64qpositionqty_;
}
 void BaseQuoteRsp::set_i64qpositionqty(::google::protobuf::uint64 value) {
  
  i64qpositionqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QPositionQty)
}

// optional double dQClosingPrice = 18;
void BaseQuoteRsp::clear_dqclosingprice() {
  dqclosingprice_ = 0;
}
 double BaseQuoteRsp::dqclosingprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQClosingPrice)
  return dqclosingprice_;
}
 void BaseQuoteRsp::set_dqclosingprice(double value) {
  
  dqclosingprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQClosingPrice)
}

// optional double QSettlePrice = 19;
void BaseQuoteRsp::clear_qsettleprice() {
  qsettleprice_ = 0;
}
 double BaseQuoteRsp::qsettleprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.QSettlePrice)
  return qsettleprice_;
}
 void BaseQuoteRsp::set_qsettleprice(double value) {
  
  qsettleprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.QSettlePrice)
}

// optional uint64 i64QLastQty = 20;
void BaseQuoteRsp::clear_i64qlastqty() {
  i64qlastqty_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qlastqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QLastQty)
  return i64qlastqty_;
}
 void BaseQuoteRsp::set_i64qlastqty(::google::protobuf::uint64 value) {
  
  i64qlastqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QLastQty)
}

// optional double dQBidPrice1 = 21;
void BaseQuoteRsp::clear_dqbidprice1() {
  dqbidprice1_ = 0;
}
 double BaseQuoteRsp::dqbidprice1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice1)
  return dqbidprice1_;
}
 void BaseQuoteRsp::set_dqbidprice1(double value) {
  
  dqbidprice1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice1)
}

// optional double dQBidPrice2 = 22;
void BaseQuoteRsp::clear_dqbidprice2() {
  dqbidprice2_ = 0;
}
 double BaseQuoteRsp::dqbidprice2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice2)
  return dqbidprice2_;
}
 void BaseQuoteRsp::set_dqbidprice2(double value) {
  
  dqbidprice2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice2)
}

// optional double dQBidPrice3 = 23;
void BaseQuoteRsp::clear_dqbidprice3() {
  dqbidprice3_ = 0;
}
 double BaseQuoteRsp::dqbidprice3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice3)
  return dqbidprice3_;
}
 void BaseQuoteRsp::set_dqbidprice3(double value) {
  
  dqbidprice3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice3)
}

// optional double dQBidPrice4 = 24;
void BaseQuoteRsp::clear_dqbidprice4() {
  dqbidprice4_ = 0;
}
 double BaseQuoteRsp::dqbidprice4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice4)
  return dqbidprice4_;
}
 void BaseQuoteRsp::set_dqbidprice4(double value) {
  
  dqbidprice4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice4)
}

// optional double dQBidPrice5 = 25;
void BaseQuoteRsp::clear_dqbidprice5() {
  dqbidprice5_ = 0;
}
 double BaseQuoteRsp::dqbidprice5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice5)
  return dqbidprice5_;
}
 void BaseQuoteRsp::set_dqbidprice5(double value) {
  
  dqbidprice5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice5)
}

// optional uint64 i64QBidQty1 = 26;
void BaseQuoteRsp::clear_i64qbidqty1() {
  i64qbidqty1_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty1)
  return i64qbidqty1_;
}
 void BaseQuoteRsp::set_i64qbidqty1(::google::protobuf::uint64 value) {
  
  i64qbidqty1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty1)
}

// optional uint64 i64QBidQty2 = 27;
void BaseQuoteRsp::clear_i64qbidqty2() {
  i64qbidqty2_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty2)
  return i64qbidqty2_;
}
 void BaseQuoteRsp::set_i64qbidqty2(::google::protobuf::uint64 value) {
  
  i64qbidqty2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty2)
}

// optional uint64 i64QBidQty3 = 28;
void BaseQuoteRsp::clear_i64qbidqty3() {
  i64qbidqty3_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty3)
  return i64qbidqty3_;
}
 void BaseQuoteRsp::set_i64qbidqty3(::google::protobuf::uint64 value) {
  
  i64qbidqty3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty3)
}

// optional uint64 i64QBidQty4 = 29;
void BaseQuoteRsp::clear_i64qbidqty4() {
  i64qbidqty4_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty4)
  return i64qbidqty4_;
}
 void BaseQuoteRsp::set_i64qbidqty4(::google::protobuf::uint64 value) {
  
  i64qbidqty4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty4)
}

// optional uint64 i64QBidQty5 = 30;
void BaseQuoteRsp::clear_i64qbidqty5() {
  i64qbidqty5_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty5)
  return i64qbidqty5_;
}
 void BaseQuoteRsp::set_i64qbidqty5(::google::protobuf::uint64 value) {
  
  i64qbidqty5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty5)
}

// optional double dQAskPrice1 = 31;
void BaseQuoteRsp::clear_dqaskprice1() {
  dqaskprice1_ = 0;
}
 double BaseQuoteRsp::dqaskprice1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice1)
  return dqaskprice1_;
}
 void BaseQuoteRsp::set_dqaskprice1(double value) {
  
  dqaskprice1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice1)
}

// optional double dQAskPrice2 = 32;
void BaseQuoteRsp::clear_dqaskprice2() {
  dqaskprice2_ = 0;
}
 double BaseQuoteRsp::dqaskprice2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice2)
  return dqaskprice2_;
}
 void BaseQuoteRsp::set_dqaskprice2(double value) {
  
  dqaskprice2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice2)
}

// optional double dQAskPrice3 = 33;
void BaseQuoteRsp::clear_dqaskprice3() {
  dqaskprice3_ = 0;
}
 double BaseQuoteRsp::dqaskprice3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice3)
  return dqaskprice3_;
}
 void BaseQuoteRsp::set_dqaskprice3(double value) {
  
  dqaskprice3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice3)
}

// optional double dQAskPrice4 = 34;
void BaseQuoteRsp::clear_dqaskprice4() {
  dqaskprice4_ = 0;
}
 double BaseQuoteRsp::dqaskprice4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice4)
  return dqaskprice4_;
}
 void BaseQuoteRsp::set_dqaskprice4(double value) {
  
  dqaskprice4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice4)
}

// optional double dQAskPrice5 = 35;
void BaseQuoteRsp::clear_dqaskprice5() {
  dqaskprice5_ = 0;
}
 double BaseQuoteRsp::dqaskprice5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice5)
  return dqaskprice5_;
}
 void BaseQuoteRsp::set_dqaskprice5(double value) {
  
  dqaskprice5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice5)
}

// optional uint64 i64QAskQty1 = 36;
void BaseQuoteRsp::clear_i64qaskqty1() {
  i64qaskqty1_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty1)
  return i64qaskqty1_;
}
 void BaseQuoteRsp::set_i64qaskqty1(::google::protobuf::uint64 value) {
  
  i64qaskqty1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty1)
}

// optional uint64 i64QAskQty2 = 37;
void BaseQuoteRsp::clear_i64qaskqty2() {
  i64qaskqty2_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty2)
  return i64qaskqty2_;
}
 void BaseQuoteRsp::set_i64qaskqty2(::google::protobuf::uint64 value) {
  
  i64qaskqty2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty2)
}

// optional uint64 i64QAskQty3 = 38;
void BaseQuoteRsp::clear_i64qaskqty3() {
  i64qaskqty3_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty3)
  return i64qaskqty3_;
}
 void BaseQuoteRsp::set_i64qaskqty3(::google::protobuf::uint64 value) {
  
  i64qaskqty3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty3)
}

// optional uint64 i64QAskQty4 = 39;
void BaseQuoteRsp::clear_i64qaskqty4() {
  i64qaskqty4_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty4)
  return i64qaskqty4_;
}
 void BaseQuoteRsp::set_i64qaskqty4(::google::protobuf::uint64 value) {
  
  i64qaskqty4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty4)
}

// optional uint64 i64QAskQty5 = 40;
void BaseQuoteRsp::clear_i64qaskqty5() {
  i64qaskqty5_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty5)
  return i64qaskqty5_;
}
 void BaseQuoteRsp::set_i64qaskqty5(::google::protobuf::uint64 value) {
  
  i64qaskqty5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty5)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OptionQuoteRsp::kBaseQuoteFieldNumber;
const int OptionQuoteRsp::kStrCallOrPutFlagFieldNumber;
const int OptionQuoteRsp::kStrStrikePriceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OptionQuoteRsp::OptionQuoteRsp()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ExchangeQuoteMessage.OptionQuoteRsp)
}

void OptionQuoteRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  basequote_ = const_cast< ::ExchangeQuoteMessage::BaseQuoteRsp*>(
      ::ExchangeQuoteMessage::BaseQuoteRsp::internal_default_instance());
#else
  basequote_ = const_cast< ::ExchangeQuoteMessage::BaseQuoteRsp*>(&::ExchangeQuoteMessage::BaseQuoteRsp::default_instance());
#endif
}

OptionQuoteRsp::OptionQuoteRsp(const OptionQuoteRsp& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ExchangeQuoteMessage.OptionQuoteRsp)
}

void OptionQuoteRsp::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  basequote_ = NULL;
  strcallorputflag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

OptionQuoteRsp::~OptionQuoteRsp() {
  // @@protoc_insertion_point(destructor:ExchangeQuoteMessage.OptionQuoteRsp)
  SharedDtor();
}

void OptionQuoteRsp::SharedDtor() {
  strcallorputflag_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete basequote_;
  }
}

void OptionQuoteRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const OptionQuoteRsp& OptionQuoteRsp::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
#endif
  return *default_instance_;
}

OptionQuoteRsp* OptionQuoteRsp::default_instance_ = NULL;

OptionQuoteRsp* OptionQuoteRsp::New(::google::protobuf::Arena* arena) const {
  OptionQuoteRsp* n = new OptionQuoteRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OptionQuoteRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:ExchangeQuoteMessage.OptionQuoteRsp)
  if (GetArenaNoVirtual() == NULL && basequote_ != NULL) delete basequote_;
  basequote_ = NULL;
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool OptionQuoteRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ExchangeQuoteMessage.OptionQuoteRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_basequote()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_strCallOrPutFlag;
        break;
      }

      // optional bytes strCallOrPutFlag = 2;
      case 2: {
        if (tag == 18) {
         parse_strCallOrPutFlag:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcallorputflag()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_strStrikePrice;
        break;
      }

      // optional bytes strStrikePrice = 3;
      case 3: {
        if (tag == 26) {
         parse_strStrikePrice:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strstrikeprice()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ExchangeQuoteMessage.OptionQuoteRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ExchangeQuoteMessage.OptionQuoteRsp)
  return false;
#undef DO_
}

void OptionQuoteRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ExchangeQuoteMessage.OptionQuoteRsp)
  // optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
  if (this->has_basequote()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, *this->basequote_, output);
  }

  // optional bytes strCallOrPutFlag = 2;
  if (this->strcallorputflag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->strcallorputflag(), output);
  }

  // optional bytes strStrikePrice = 3;
  if (this->strstrikeprice().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->strstrikeprice(), output);
  }

  // @@protoc_insertion_point(serialize_end:ExchangeQuoteMessage.OptionQuoteRsp)
}

int OptionQuoteRsp::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ExchangeQuoteMessage.OptionQuoteRsp)
  int total_size = 0;

  // optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
  if (this->has_basequote()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->basequote_);
  }

  // optional bytes strCallOrPutFlag = 2;
  if (this->strcallorputflag().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcallorputflag());
  }

  // optional bytes strStrikePrice = 3;
  if (this->strstrikeprice().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strstrikeprice());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OptionQuoteRsp::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const OptionQuoteRsp*>(&from));
}

void OptionQuoteRsp::MergeFrom(const OptionQuoteRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ExchangeQuoteMessage.OptionQuoteRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_basequote()) {
    mutable_basequote()->::ExchangeQuoteMessage::BaseQuoteRsp::MergeFrom(from.basequote());
  }
  if (from.strcallorputflag().size() > 0) {

    strcallorputflag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcallorputflag_);
  }
  if (from.strstrikeprice().size() > 0) {

    strstrikeprice_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strstrikeprice_);
  }
}

void OptionQuoteRsp::CopyFrom(const OptionQuoteRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExchangeQuoteMessage.OptionQuoteRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OptionQuoteRsp::IsInitialized() const {

  return true;
}

void OptionQuoteRsp::Swap(OptionQuoteRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OptionQuoteRsp::InternalSwap(OptionQuoteRsp* other) {
  std::swap(basequote_, other->basequote_);
  strcallorputflag_.Swap(&other->strcallorputflag_);
  strstrikeprice_.Swap(&other->strstrikeprice_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string OptionQuoteRsp::GetTypeName() const {
  return "ExchangeQuoteMessage.OptionQuoteRsp";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OptionQuoteRsp

// optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
bool OptionQuoteRsp::has_basequote() const {
  return !_is_default_instance_ && basequote_ != NULL;
}
void OptionQuoteRsp::clear_basequote() {
  if (GetArenaNoVirtual() == NULL && basequote_ != NULL) delete basequote_;
  basequote_ = NULL;
}
const ::ExchangeQuoteMessage::BaseQuoteRsp& OptionQuoteRsp::basequote() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return basequote_ != NULL ? *basequote_ : *default_instance().basequote_;
#else
  return basequote_ != NULL ? *basequote_ : *default_instance_->basequote_;
#endif
}
::ExchangeQuoteMessage::BaseQuoteRsp* OptionQuoteRsp::mutable_basequote() {
  
  if (basequote_ == NULL) {
    basequote_ = new ::ExchangeQuoteMessage::BaseQuoteRsp;
  }
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
  return basequote_;
}
::ExchangeQuoteMessage::BaseQuoteRsp* OptionQuoteRsp::release_basequote() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
  
  ::ExchangeQuoteMessage::BaseQuoteRsp* temp = basequote_;
  basequote_ = NULL;
  return temp;
}
void OptionQuoteRsp::set_allocated_basequote(::ExchangeQuoteMessage::BaseQuoteRsp* basequote) {
  delete basequote_;
  basequote_ = basequote;
  if (basequote) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
}

// optional bytes strCallOrPutFlag = 2;
void OptionQuoteRsp::clear_strcallorputflag() {
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& OptionQuoteRsp::strcallorputflag() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  return strcallorputflag_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OptionQuoteRsp::set_strcallorputflag(const ::std::string& value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
 void OptionQuoteRsp::set_strcallorputflag(const char* value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
 void OptionQuoteRsp::set_strcallorputflag(const void* value, size_t size) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
 ::std::string* OptionQuoteRsp::mutable_strcallorputflag() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  return strcallorputflag_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* OptionQuoteRsp::release_strcallorputflag() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  
  return strcallorputflag_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OptionQuoteRsp::set_allocated_strcallorputflag(::std::string* strcallorputflag) {
  if (strcallorputflag != NULL) {
    
  } else {
    
  }
  strcallorputflag_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcallorputflag);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}

// optional bytes strStrikePrice = 3;
void OptionQuoteRsp::clear_strstrikeprice() {
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& OptionQuoteRsp::strstrikeprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  return strstrikeprice_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OptionQuoteRsp::set_strstrikeprice(const ::std::string& value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
 void OptionQuoteRsp::set_strstrikeprice(const char* value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
 void OptionQuoteRsp::set_strstrikeprice(const void* value, size_t size) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
 ::std::string* OptionQuoteRsp::mutable_strstrikeprice() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  return strstrikeprice_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* OptionQuoteRsp::release_strstrikeprice() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  
  return strstrikeprice_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OptionQuoteRsp::set_allocated_strstrikeprice(::std::string* strstrikeprice) {
  if (strstrikeprice != NULL) {
    
  } else {
    
  }
  strstrikeprice_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strstrikeprice);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ExchangeQuoteMessage

// @@protoc_insertion_point(global_scope)
