// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbExchangeQuoteMessage.proto

#ifndef PROTOBUF_pbExchangeQuoteMessage_2eproto__INCLUDED
#define PROTOBUF_pbExchangeQuoteMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace ExchangeQuoteMessage {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
void protobuf_AssignDesc_pbExchangeQuoteMessage_2eproto();
void protobuf_ShutdownFile_pbExchangeQuoteMessage_2eproto();

class BaseQuoteRsp;
class OptionQuoteRsp;

// ===================================================================

class BaseQuoteRsp : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:ExchangeQuoteMessage.BaseQuoteRsp) */ {
 public:
  BaseQuoteRsp();
  virtual ~BaseQuoteRsp();

  BaseQuoteRsp(const BaseQuoteRsp& from);

  inline BaseQuoteRsp& operator=(const BaseQuoteRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const BaseQuoteRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BaseQuoteRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BaseQuoteRsp* other);

  // implements Message ----------------------------------------------

  inline BaseQuoteRsp* New() const { return New(NULL); }

  BaseQuoteRsp* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BaseQuoteRsp& from);
  void MergeFrom(const BaseQuoteRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BaseQuoteRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes strTradeDate = 1;
  void clear_strtradedate();
  static const int kStrTradeDateFieldNumber = 1;
  const ::std::string& strtradedate() const;
  void set_strtradedate(const ::std::string& value);
  void set_strtradedate(const char* value);
  void set_strtradedate(const void* value, size_t size);
  ::std::string* mutable_strtradedate();
  ::std::string* release_strtradedate();
  void set_allocated_strtradedate(::std::string* strtradedate);

  // optional bytes strExchange = 2;
  void clear_strexchange();
  static const int kStrExchangeFieldNumber = 2;
  const ::std::string& strexchange() const;
  void set_strexchange(const ::std::string& value);
  void set_strexchange(const char* value);
  void set_strexchange(const void* value, size_t size);
  ::std::string* mutable_strexchange();
  ::std::string* release_strexchange();
  void set_allocated_strexchange(::std::string* strexchange);

  // optional bytes strComodity = 3;
  void clear_strcomodity();
  static const int kStrComodityFieldNumber = 3;
  const ::std::string& strcomodity() const;
  void set_strcomodity(const ::std::string& value);
  void set_strcomodity(const char* value);
  void set_strcomodity(const void* value, size_t size);
  ::std::string* mutable_strcomodity();
  ::std::string* release_strcomodity();
  void set_allocated_strcomodity(::std::string* strcomodity);

  // optional bytes strContractNo = 4;
  void clear_strcontractno();
  static const int kStrContractNoFieldNumber = 4;
  const ::std::string& strcontractno() const;
  void set_strcontractno(const ::std::string& value);
  void set_strcontractno(const char* value);
  void set_strcontractno(const void* value, size_t size);
  ::std::string* mutable_strcontractno();
  ::std::string* release_strcontractno();
  void set_allocated_strcontractno(::std::string* strcontractno);

  // optional bytes strDateTimeStamp = 5;
  void clear_strdatetimestamp();
  static const int kStrDateTimeStampFieldNumber = 5;
  const ::std::string& strdatetimestamp() const;
  void set_strdatetimestamp(const ::std::string& value);
  void set_strdatetimestamp(const char* value);
  void set_strdatetimestamp(const void* value, size_t size);
  ::std::string* mutable_strdatetimestamp();
  ::std::string* release_strdatetimestamp();
  void set_allocated_strdatetimestamp(::std::string* strdatetimestamp);

  // optional bytes strMiliSec = 6;
  void clear_strmilisec();
  static const int kStrMiliSecFieldNumber = 6;
  const ::std::string& strmilisec() const;
  void set_strmilisec(const ::std::string& value);
  void set_strmilisec(const char* value);
  void set_strmilisec(const void* value, size_t size);
  ::std::string* mutable_strmilisec();
  ::std::string* release_strmilisec();
  void set_allocated_strmilisec(::std::string* strmilisec);

  // optional double dQPreClosingPrice = 7;
  void clear_dqpreclosingprice();
  static const int kDQPreClosingPriceFieldNumber = 7;
  double dqpreclosingprice() const;
  void set_dqpreclosingprice(double value);

  // optional double dQPreSettlePrice = 8;
  void clear_dqpresettleprice();
  static const int kDQPreSettlePriceFieldNumber = 8;
  double dqpresettleprice() const;
  void set_dqpresettleprice(double value);

  // optional uint64 i64QPrePositionQty = 9;
  void clear_i64qprepositionqty();
  static const int kI64QPrePositionQtyFieldNumber = 9;
  ::google::protobuf::uint64 i64qprepositionqty() const;
  void set_i64qprepositionqty(::google::protobuf::uint64 value);

  // optional double dQOpeningPrice = 10;
  void clear_dqopeningprice();
  static const int kDQOpeningPriceFieldNumber = 10;
  double dqopeningprice() const;
  void set_dqopeningprice(double value);

  // optional double dQLastPrice = 11;
  void clear_dqlastprice();
  static const int kDQLastPriceFieldNumber = 11;
  double dqlastprice() const;
  void set_dqlastprice(double value);

  // optional double dQHighPrice = 12;
  void clear_dqhighprice();
  static const int kDQHighPriceFieldNumber = 12;
  double dqhighprice() const;
  void set_dqhighprice(double value);

  // optional double dQLowPrice = 13;
  void clear_dqlowprice();
  static const int kDQLowPriceFieldNumber = 13;
  double dqlowprice() const;
  void set_dqlowprice(double value);

  // optional double dQLimitUpPrice = 14;
  void clear_dqlimitupprice();
  static const int kDQLimitUpPriceFieldNumber = 14;
  double dqlimitupprice() const;
  void set_dqlimitupprice(double value);

  // optional double dQLimitDownPrice = 15;
  void clear_dqlimitdownprice();
  static const int kDQLimitDownPriceFieldNumber = 15;
  double dqlimitdownprice() const;
  void set_dqlimitdownprice(double value);

  // optional uint64 i64QTotalQty = 16;
  void clear_i64qtotalqty();
  static const int kI64QTotalQtyFieldNumber = 16;
  ::google::protobuf::uint64 i64qtotalqty() const;
  void set_i64qtotalqty(::google::protobuf::uint64 value);

  // optional uint64 i64QPositionQty = 17;
  void clear_i64qpositionqty();
  static const int kI64QPositionQtyFieldNumber = 17;
  ::google::protobuf::uint64 i64qpositionqty() const;
  void set_i64qpositionqty(::google::protobuf::uint64 value);

  // optional double dQClosingPrice = 18;
  void clear_dqclosingprice();
  static const int kDQClosingPriceFieldNumber = 18;
  double dqclosingprice() const;
  void set_dqclosingprice(double value);

  // optional double QSettlePrice = 19;
  void clear_qsettleprice();
  static const int kQSettlePriceFieldNumber = 19;
  double qsettleprice() const;
  void set_qsettleprice(double value);

  // optional uint64 i64QLastQty = 20;
  void clear_i64qlastqty();
  static const int kI64QLastQtyFieldNumber = 20;
  ::google::protobuf::uint64 i64qlastqty() const;
  void set_i64qlastqty(::google::protobuf::uint64 value);

  // optional double dQBidPrice1 = 21;
  void clear_dqbidprice1();
  static const int kDQBidPrice1FieldNumber = 21;
  double dqbidprice1() const;
  void set_dqbidprice1(double value);

  // optional double dQBidPrice2 = 22;
  void clear_dqbidprice2();
  static const int kDQBidPrice2FieldNumber = 22;
  double dqbidprice2() const;
  void set_dqbidprice2(double value);

  // optional double dQBidPrice3 = 23;
  void clear_dqbidprice3();
  static const int kDQBidPrice3FieldNumber = 23;
  double dqbidprice3() const;
  void set_dqbidprice3(double value);

  // optional double dQBidPrice4 = 24;
  void clear_dqbidprice4();
  static const int kDQBidPrice4FieldNumber = 24;
  double dqbidprice4() const;
  void set_dqbidprice4(double value);

  // optional double dQBidPrice5 = 25;
  void clear_dqbidprice5();
  static const int kDQBidPrice5FieldNumber = 25;
  double dqbidprice5() const;
  void set_dqbidprice5(double value);

  // optional uint64 i64QBidQty1 = 26;
  void clear_i64qbidqty1();
  static const int kI64QBidQty1FieldNumber = 26;
  ::google::protobuf::uint64 i64qbidqty1() const;
  void set_i64qbidqty1(::google::protobuf::uint64 value);

  // optional uint64 i64QBidQty2 = 27;
  void clear_i64qbidqty2();
  static const int kI64QBidQty2FieldNumber = 27;
  ::google::protobuf::uint64 i64qbidqty2() const;
  void set_i64qbidqty2(::google::protobuf::uint64 value);

  // optional uint64 i64QBidQty3 = 28;
  void clear_i64qbidqty3();
  static const int kI64QBidQty3FieldNumber = 28;
  ::google::protobuf::uint64 i64qbidqty3() const;
  void set_i64qbidqty3(::google::protobuf::uint64 value);

  // optional uint64 i64QBidQty4 = 29;
  void clear_i64qbidqty4();
  static const int kI64QBidQty4FieldNumber = 29;
  ::google::protobuf::uint64 i64qbidqty4() const;
  void set_i64qbidqty4(::google::protobuf::uint64 value);

  // optional uint64 i64QBidQty5 = 30;
  void clear_i64qbidqty5();
  static const int kI64QBidQty5FieldNumber = 30;
  ::google::protobuf::uint64 i64qbidqty5() const;
  void set_i64qbidqty5(::google::protobuf::uint64 value);

  // optional double dQAskPrice1 = 31;
  void clear_dqaskprice1();
  static const int kDQAskPrice1FieldNumber = 31;
  double dqaskprice1() const;
  void set_dqaskprice1(double value);

  // optional double dQAskPrice2 = 32;
  void clear_dqaskprice2();
  static const int kDQAskPrice2FieldNumber = 32;
  double dqaskprice2() const;
  void set_dqaskprice2(double value);

  // optional double dQAskPrice3 = 33;
  void clear_dqaskprice3();
  static const int kDQAskPrice3FieldNumber = 33;
  double dqaskprice3() const;
  void set_dqaskprice3(double value);

  // optional double dQAskPrice4 = 34;
  void clear_dqaskprice4();
  static const int kDQAskPrice4FieldNumber = 34;
  double dqaskprice4() const;
  void set_dqaskprice4(double value);

  // optional double dQAskPrice5 = 35;
  void clear_dqaskprice5();
  static const int kDQAskPrice5FieldNumber = 35;
  double dqaskprice5() const;
  void set_dqaskprice5(double value);

  // optional uint64 i64QAskQty1 = 36;
  void clear_i64qaskqty1();
  static const int kI64QAskQty1FieldNumber = 36;
  ::google::protobuf::uint64 i64qaskqty1() const;
  void set_i64qaskqty1(::google::protobuf::uint64 value);

  // optional uint64 i64QAskQty2 = 37;
  void clear_i64qaskqty2();
  static const int kI64QAskQty2FieldNumber = 37;
  ::google::protobuf::uint64 i64qaskqty2() const;
  void set_i64qaskqty2(::google::protobuf::uint64 value);

  // optional uint64 i64QAskQty3 = 38;
  void clear_i64qaskqty3();
  static const int kI64QAskQty3FieldNumber = 38;
  ::google::protobuf::uint64 i64qaskqty3() const;
  void set_i64qaskqty3(::google::protobuf::uint64 value);

  // optional uint64 i64QAskQty4 = 39;
  void clear_i64qaskqty4();
  static const int kI64QAskQty4FieldNumber = 39;
  ::google::protobuf::uint64 i64qaskqty4() const;
  void set_i64qaskqty4(::google::protobuf::uint64 value);

  // optional uint64 i64QAskQty5 = 40;
  void clear_i64qaskqty5();
  static const int kI64QAskQty5FieldNumber = 40;
  ::google::protobuf::uint64 i64qaskqty5() const;
  void set_i64qaskqty5(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:ExchangeQuoteMessage.BaseQuoteRsp)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr strtradedate_;
  ::google::protobuf::internal::ArenaStringPtr strexchange_;
  ::google::protobuf::internal::ArenaStringPtr strcomodity_;
  ::google::protobuf::internal::ArenaStringPtr strcontractno_;
  ::google::protobuf::internal::ArenaStringPtr strdatetimestamp_;
  ::google::protobuf::internal::ArenaStringPtr strmilisec_;
  double dqpreclosingprice_;
  double dqpresettleprice_;
  ::google::protobuf::uint64 i64qprepositionqty_;
  double dqopeningprice_;
  double dqlastprice_;
  double dqhighprice_;
  double dqlowprice_;
  double dqlimitupprice_;
  double dqlimitdownprice_;
  ::google::protobuf::uint64 i64qtotalqty_;
  ::google::protobuf::uint64 i64qpositionqty_;
  double dqclosingprice_;
  double qsettleprice_;
  ::google::protobuf::uint64 i64qlastqty_;
  double dqbidprice1_;
  double dqbidprice2_;
  double dqbidprice3_;
  double dqbidprice4_;
  double dqbidprice5_;
  ::google::protobuf::uint64 i64qbidqty1_;
  ::google::protobuf::uint64 i64qbidqty2_;
  ::google::protobuf::uint64 i64qbidqty3_;
  ::google::protobuf::uint64 i64qbidqty4_;
  ::google::protobuf::uint64 i64qbidqty5_;
  double dqaskprice1_;
  double dqaskprice2_;
  double dqaskprice3_;
  double dqaskprice4_;
  double dqaskprice5_;
  ::google::protobuf::uint64 i64qaskqty1_;
  ::google::protobuf::uint64 i64qaskqty2_;
  ::google::protobuf::uint64 i64qaskqty3_;
  ::google::protobuf::uint64 i64qaskqty4_;
  ::google::protobuf::uint64 i64qaskqty5_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbExchangeQuoteMessage_2eproto();
  friend void protobuf_ShutdownFile_pbExchangeQuoteMessage_2eproto();

  void InitAsDefaultInstance();
  static BaseQuoteRsp* default_instance_;
};
// -------------------------------------------------------------------

class OptionQuoteRsp : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:ExchangeQuoteMessage.OptionQuoteRsp) */ {
 public:
  OptionQuoteRsp();
  virtual ~OptionQuoteRsp();

  OptionQuoteRsp(const OptionQuoteRsp& from);

  inline OptionQuoteRsp& operator=(const OptionQuoteRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const OptionQuoteRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const OptionQuoteRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(OptionQuoteRsp* other);

  // implements Message ----------------------------------------------

  inline OptionQuoteRsp* New() const { return New(NULL); }

  OptionQuoteRsp* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const OptionQuoteRsp& from);
  void MergeFrom(const OptionQuoteRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OptionQuoteRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
  bool has_basequote() const;
  void clear_basequote();
  static const int kBaseQuoteFieldNumber = 1;
  const ::ExchangeQuoteMessage::BaseQuoteRsp& basequote() const;
  ::ExchangeQuoteMessage::BaseQuoteRsp* mutable_basequote();
  ::ExchangeQuoteMessage::BaseQuoteRsp* release_basequote();
  void set_allocated_basequote(::ExchangeQuoteMessage::BaseQuoteRsp* basequote);

  // optional bytes strCallOrPutFlag = 2;
  void clear_strcallorputflag();
  static const int kStrCallOrPutFlagFieldNumber = 2;
  const ::std::string& strcallorputflag() const;
  void set_strcallorputflag(const ::std::string& value);
  void set_strcallorputflag(const char* value);
  void set_strcallorputflag(const void* value, size_t size);
  ::std::string* mutable_strcallorputflag();
  ::std::string* release_strcallorputflag();
  void set_allocated_strcallorputflag(::std::string* strcallorputflag);

  // optional bytes strStrikePrice = 3;
  void clear_strstrikeprice();
  static const int kStrStrikePriceFieldNumber = 3;
  const ::std::string& strstrikeprice() const;
  void set_strstrikeprice(const ::std::string& value);
  void set_strstrikeprice(const char* value);
  void set_strstrikeprice(const void* value, size_t size);
  ::std::string* mutable_strstrikeprice();
  ::std::string* release_strstrikeprice();
  void set_allocated_strstrikeprice(::std::string* strstrikeprice);

  // @@protoc_insertion_point(class_scope:ExchangeQuoteMessage.OptionQuoteRsp)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::ExchangeQuoteMessage::BaseQuoteRsp* basequote_;
  ::google::protobuf::internal::ArenaStringPtr strcallorputflag_;
  ::google::protobuf::internal::ArenaStringPtr strstrikeprice_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbExchangeQuoteMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbExchangeQuoteMessage_2eproto();
  friend void protobuf_ShutdownFile_pbExchangeQuoteMessage_2eproto();

  void InitAsDefaultInstance();
  static OptionQuoteRsp* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BaseQuoteRsp

// optional bytes strTradeDate = 1;
inline void BaseQuoteRsp::clear_strtradedate() {
  strtradedate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strtradedate() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  return strtradedate_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strtradedate(const ::std::string& value) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
inline void BaseQuoteRsp::set_strtradedate(const char* value) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
inline void BaseQuoteRsp::set_strtradedate(const void* value, size_t size) {
  
  strtradedate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}
inline ::std::string* BaseQuoteRsp::mutable_strtradedate() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  return strtradedate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strtradedate() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
  
  return strtradedate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strtradedate(::std::string* strtradedate) {
  if (strtradedate != NULL) {
    
  } else {
    
  }
  strtradedate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strtradedate);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strTradeDate)
}

// optional bytes strExchange = 2;
inline void BaseQuoteRsp::clear_strexchange() {
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strexchange() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  return strexchange_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strexchange(const ::std::string& value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
inline void BaseQuoteRsp::set_strexchange(const char* value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
inline void BaseQuoteRsp::set_strexchange(const void* value, size_t size) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}
inline ::std::string* BaseQuoteRsp::mutable_strexchange() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  return strexchange_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strexchange() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
  
  return strexchange_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strexchange(::std::string* strexchange) {
  if (strexchange != NULL) {
    
  } else {
    
  }
  strexchange_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strexchange);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strExchange)
}

// optional bytes strComodity = 3;
inline void BaseQuoteRsp::clear_strcomodity() {
  strcomodity_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strcomodity() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  return strcomodity_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strcomodity(const ::std::string& value) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
inline void BaseQuoteRsp::set_strcomodity(const char* value) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
inline void BaseQuoteRsp::set_strcomodity(const void* value, size_t size) {
  
  strcomodity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}
inline ::std::string* BaseQuoteRsp::mutable_strcomodity() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  return strcomodity_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strcomodity() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
  
  return strcomodity_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strcomodity(::std::string* strcomodity) {
  if (strcomodity != NULL) {
    
  } else {
    
  }
  strcomodity_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcomodity);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strComodity)
}

// optional bytes strContractNo = 4;
inline void BaseQuoteRsp::clear_strcontractno() {
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strcontractno() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  return strcontractno_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strcontractno(const ::std::string& value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
inline void BaseQuoteRsp::set_strcontractno(const char* value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
inline void BaseQuoteRsp::set_strcontractno(const void* value, size_t size) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}
inline ::std::string* BaseQuoteRsp::mutable_strcontractno() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  return strcontractno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strcontractno() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
  
  return strcontractno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strcontractno(::std::string* strcontractno) {
  if (strcontractno != NULL) {
    
  } else {
    
  }
  strcontractno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcontractno);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strContractNo)
}

// optional bytes strDateTimeStamp = 5;
inline void BaseQuoteRsp::clear_strdatetimestamp() {
  strdatetimestamp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strdatetimestamp() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  return strdatetimestamp_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strdatetimestamp(const ::std::string& value) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
inline void BaseQuoteRsp::set_strdatetimestamp(const char* value) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
inline void BaseQuoteRsp::set_strdatetimestamp(const void* value, size_t size) {
  
  strdatetimestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}
inline ::std::string* BaseQuoteRsp::mutable_strdatetimestamp() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  return strdatetimestamp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strdatetimestamp() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
  
  return strdatetimestamp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strdatetimestamp(::std::string* strdatetimestamp) {
  if (strdatetimestamp != NULL) {
    
  } else {
    
  }
  strdatetimestamp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strdatetimestamp);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strDateTimeStamp)
}

// optional bytes strMiliSec = 6;
inline void BaseQuoteRsp::clear_strmilisec() {
  strmilisec_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseQuoteRsp::strmilisec() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  return strmilisec_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_strmilisec(const ::std::string& value) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
inline void BaseQuoteRsp::set_strmilisec(const char* value) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
inline void BaseQuoteRsp::set_strmilisec(const void* value, size_t size) {
  
  strmilisec_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}
inline ::std::string* BaseQuoteRsp::mutable_strmilisec() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  return strmilisec_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseQuoteRsp::release_strmilisec() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
  
  return strmilisec_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseQuoteRsp::set_allocated_strmilisec(::std::string* strmilisec) {
  if (strmilisec != NULL) {
    
  } else {
    
  }
  strmilisec_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strmilisec);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.BaseQuoteRsp.strMiliSec)
}

// optional double dQPreClosingPrice = 7;
inline void BaseQuoteRsp::clear_dqpreclosingprice() {
  dqpreclosingprice_ = 0;
}
inline double BaseQuoteRsp::dqpreclosingprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQPreClosingPrice)
  return dqpreclosingprice_;
}
inline void BaseQuoteRsp::set_dqpreclosingprice(double value) {
  
  dqpreclosingprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQPreClosingPrice)
}

// optional double dQPreSettlePrice = 8;
inline void BaseQuoteRsp::clear_dqpresettleprice() {
  dqpresettleprice_ = 0;
}
inline double BaseQuoteRsp::dqpresettleprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQPreSettlePrice)
  return dqpresettleprice_;
}
inline void BaseQuoteRsp::set_dqpresettleprice(double value) {
  
  dqpresettleprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQPreSettlePrice)
}

// optional uint64 i64QPrePositionQty = 9;
inline void BaseQuoteRsp::clear_i64qprepositionqty() {
  i64qprepositionqty_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qprepositionqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QPrePositionQty)
  return i64qprepositionqty_;
}
inline void BaseQuoteRsp::set_i64qprepositionqty(::google::protobuf::uint64 value) {
  
  i64qprepositionqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QPrePositionQty)
}

// optional double dQOpeningPrice = 10;
inline void BaseQuoteRsp::clear_dqopeningprice() {
  dqopeningprice_ = 0;
}
inline double BaseQuoteRsp::dqopeningprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQOpeningPrice)
  return dqopeningprice_;
}
inline void BaseQuoteRsp::set_dqopeningprice(double value) {
  
  dqopeningprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQOpeningPrice)
}

// optional double dQLastPrice = 11;
inline void BaseQuoteRsp::clear_dqlastprice() {
  dqlastprice_ = 0;
}
inline double BaseQuoteRsp::dqlastprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLastPrice)
  return dqlastprice_;
}
inline void BaseQuoteRsp::set_dqlastprice(double value) {
  
  dqlastprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLastPrice)
}

// optional double dQHighPrice = 12;
inline void BaseQuoteRsp::clear_dqhighprice() {
  dqhighprice_ = 0;
}
inline double BaseQuoteRsp::dqhighprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQHighPrice)
  return dqhighprice_;
}
inline void BaseQuoteRsp::set_dqhighprice(double value) {
  
  dqhighprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQHighPrice)
}

// optional double dQLowPrice = 13;
inline void BaseQuoteRsp::clear_dqlowprice() {
  dqlowprice_ = 0;
}
inline double BaseQuoteRsp::dqlowprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLowPrice)
  return dqlowprice_;
}
inline void BaseQuoteRsp::set_dqlowprice(double value) {
  
  dqlowprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLowPrice)
}

// optional double dQLimitUpPrice = 14;
inline void BaseQuoteRsp::clear_dqlimitupprice() {
  dqlimitupprice_ = 0;
}
inline double BaseQuoteRsp::dqlimitupprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitUpPrice)
  return dqlimitupprice_;
}
inline void BaseQuoteRsp::set_dqlimitupprice(double value) {
  
  dqlimitupprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitUpPrice)
}

// optional double dQLimitDownPrice = 15;
inline void BaseQuoteRsp::clear_dqlimitdownprice() {
  dqlimitdownprice_ = 0;
}
inline double BaseQuoteRsp::dqlimitdownprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitDownPrice)
  return dqlimitdownprice_;
}
inline void BaseQuoteRsp::set_dqlimitdownprice(double value) {
  
  dqlimitdownprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQLimitDownPrice)
}

// optional uint64 i64QTotalQty = 16;
inline void BaseQuoteRsp::clear_i64qtotalqty() {
  i64qtotalqty_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qtotalqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QTotalQty)
  return i64qtotalqty_;
}
inline void BaseQuoteRsp::set_i64qtotalqty(::google::protobuf::uint64 value) {
  
  i64qtotalqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QTotalQty)
}

// optional uint64 i64QPositionQty = 17;
inline void BaseQuoteRsp::clear_i64qpositionqty() {
  i64qpositionqty_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qpositionqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QPositionQty)
  return i64qpositionqty_;
}
inline void BaseQuoteRsp::set_i64qpositionqty(::google::protobuf::uint64 value) {
  
  i64qpositionqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QPositionQty)
}

// optional double dQClosingPrice = 18;
inline void BaseQuoteRsp::clear_dqclosingprice() {
  dqclosingprice_ = 0;
}
inline double BaseQuoteRsp::dqclosingprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQClosingPrice)
  return dqclosingprice_;
}
inline void BaseQuoteRsp::set_dqclosingprice(double value) {
  
  dqclosingprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQClosingPrice)
}

// optional double QSettlePrice = 19;
inline void BaseQuoteRsp::clear_qsettleprice() {
  qsettleprice_ = 0;
}
inline double BaseQuoteRsp::qsettleprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.QSettlePrice)
  return qsettleprice_;
}
inline void BaseQuoteRsp::set_qsettleprice(double value) {
  
  qsettleprice_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.QSettlePrice)
}

// optional uint64 i64QLastQty = 20;
inline void BaseQuoteRsp::clear_i64qlastqty() {
  i64qlastqty_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qlastqty() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QLastQty)
  return i64qlastqty_;
}
inline void BaseQuoteRsp::set_i64qlastqty(::google::protobuf::uint64 value) {
  
  i64qlastqty_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QLastQty)
}

// optional double dQBidPrice1 = 21;
inline void BaseQuoteRsp::clear_dqbidprice1() {
  dqbidprice1_ = 0;
}
inline double BaseQuoteRsp::dqbidprice1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice1)
  return dqbidprice1_;
}
inline void BaseQuoteRsp::set_dqbidprice1(double value) {
  
  dqbidprice1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice1)
}

// optional double dQBidPrice2 = 22;
inline void BaseQuoteRsp::clear_dqbidprice2() {
  dqbidprice2_ = 0;
}
inline double BaseQuoteRsp::dqbidprice2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice2)
  return dqbidprice2_;
}
inline void BaseQuoteRsp::set_dqbidprice2(double value) {
  
  dqbidprice2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice2)
}

// optional double dQBidPrice3 = 23;
inline void BaseQuoteRsp::clear_dqbidprice3() {
  dqbidprice3_ = 0;
}
inline double BaseQuoteRsp::dqbidprice3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice3)
  return dqbidprice3_;
}
inline void BaseQuoteRsp::set_dqbidprice3(double value) {
  
  dqbidprice3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice3)
}

// optional double dQBidPrice4 = 24;
inline void BaseQuoteRsp::clear_dqbidprice4() {
  dqbidprice4_ = 0;
}
inline double BaseQuoteRsp::dqbidprice4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice4)
  return dqbidprice4_;
}
inline void BaseQuoteRsp::set_dqbidprice4(double value) {
  
  dqbidprice4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice4)
}

// optional double dQBidPrice5 = 25;
inline void BaseQuoteRsp::clear_dqbidprice5() {
  dqbidprice5_ = 0;
}
inline double BaseQuoteRsp::dqbidprice5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice5)
  return dqbidprice5_;
}
inline void BaseQuoteRsp::set_dqbidprice5(double value) {
  
  dqbidprice5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQBidPrice5)
}

// optional uint64 i64QBidQty1 = 26;
inline void BaseQuoteRsp::clear_i64qbidqty1() {
  i64qbidqty1_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty1)
  return i64qbidqty1_;
}
inline void BaseQuoteRsp::set_i64qbidqty1(::google::protobuf::uint64 value) {
  
  i64qbidqty1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty1)
}

// optional uint64 i64QBidQty2 = 27;
inline void BaseQuoteRsp::clear_i64qbidqty2() {
  i64qbidqty2_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty2)
  return i64qbidqty2_;
}
inline void BaseQuoteRsp::set_i64qbidqty2(::google::protobuf::uint64 value) {
  
  i64qbidqty2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty2)
}

// optional uint64 i64QBidQty3 = 28;
inline void BaseQuoteRsp::clear_i64qbidqty3() {
  i64qbidqty3_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty3)
  return i64qbidqty3_;
}
inline void BaseQuoteRsp::set_i64qbidqty3(::google::protobuf::uint64 value) {
  
  i64qbidqty3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty3)
}

// optional uint64 i64QBidQty4 = 29;
inline void BaseQuoteRsp::clear_i64qbidqty4() {
  i64qbidqty4_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty4)
  return i64qbidqty4_;
}
inline void BaseQuoteRsp::set_i64qbidqty4(::google::protobuf::uint64 value) {
  
  i64qbidqty4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty4)
}

// optional uint64 i64QBidQty5 = 30;
inline void BaseQuoteRsp::clear_i64qbidqty5() {
  i64qbidqty5_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qbidqty5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty5)
  return i64qbidqty5_;
}
inline void BaseQuoteRsp::set_i64qbidqty5(::google::protobuf::uint64 value) {
  
  i64qbidqty5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QBidQty5)
}

// optional double dQAskPrice1 = 31;
inline void BaseQuoteRsp::clear_dqaskprice1() {
  dqaskprice1_ = 0;
}
inline double BaseQuoteRsp::dqaskprice1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice1)
  return dqaskprice1_;
}
inline void BaseQuoteRsp::set_dqaskprice1(double value) {
  
  dqaskprice1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice1)
}

// optional double dQAskPrice2 = 32;
inline void BaseQuoteRsp::clear_dqaskprice2() {
  dqaskprice2_ = 0;
}
inline double BaseQuoteRsp::dqaskprice2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice2)
  return dqaskprice2_;
}
inline void BaseQuoteRsp::set_dqaskprice2(double value) {
  
  dqaskprice2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice2)
}

// optional double dQAskPrice3 = 33;
inline void BaseQuoteRsp::clear_dqaskprice3() {
  dqaskprice3_ = 0;
}
inline double BaseQuoteRsp::dqaskprice3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice3)
  return dqaskprice3_;
}
inline void BaseQuoteRsp::set_dqaskprice3(double value) {
  
  dqaskprice3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice3)
}

// optional double dQAskPrice4 = 34;
inline void BaseQuoteRsp::clear_dqaskprice4() {
  dqaskprice4_ = 0;
}
inline double BaseQuoteRsp::dqaskprice4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice4)
  return dqaskprice4_;
}
inline void BaseQuoteRsp::set_dqaskprice4(double value) {
  
  dqaskprice4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice4)
}

// optional double dQAskPrice5 = 35;
inline void BaseQuoteRsp::clear_dqaskprice5() {
  dqaskprice5_ = 0;
}
inline double BaseQuoteRsp::dqaskprice5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice5)
  return dqaskprice5_;
}
inline void BaseQuoteRsp::set_dqaskprice5(double value) {
  
  dqaskprice5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.dQAskPrice5)
}

// optional uint64 i64QAskQty1 = 36;
inline void BaseQuoteRsp::clear_i64qaskqty1() {
  i64qaskqty1_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty1() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty1)
  return i64qaskqty1_;
}
inline void BaseQuoteRsp::set_i64qaskqty1(::google::protobuf::uint64 value) {
  
  i64qaskqty1_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty1)
}

// optional uint64 i64QAskQty2 = 37;
inline void BaseQuoteRsp::clear_i64qaskqty2() {
  i64qaskqty2_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty2() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty2)
  return i64qaskqty2_;
}
inline void BaseQuoteRsp::set_i64qaskqty2(::google::protobuf::uint64 value) {
  
  i64qaskqty2_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty2)
}

// optional uint64 i64QAskQty3 = 38;
inline void BaseQuoteRsp::clear_i64qaskqty3() {
  i64qaskqty3_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty3() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty3)
  return i64qaskqty3_;
}
inline void BaseQuoteRsp::set_i64qaskqty3(::google::protobuf::uint64 value) {
  
  i64qaskqty3_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty3)
}

// optional uint64 i64QAskQty4 = 39;
inline void BaseQuoteRsp::clear_i64qaskqty4() {
  i64qaskqty4_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty4() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty4)
  return i64qaskqty4_;
}
inline void BaseQuoteRsp::set_i64qaskqty4(::google::protobuf::uint64 value) {
  
  i64qaskqty4_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty4)
}

// optional uint64 i64QAskQty5 = 40;
inline void BaseQuoteRsp::clear_i64qaskqty5() {
  i64qaskqty5_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseQuoteRsp::i64qaskqty5() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty5)
  return i64qaskqty5_;
}
inline void BaseQuoteRsp::set_i64qaskqty5(::google::protobuf::uint64 value) {
  
  i64qaskqty5_ = value;
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.BaseQuoteRsp.i64QAskQty5)
}

// -------------------------------------------------------------------

// OptionQuoteRsp

// optional .ExchangeQuoteMessage.BaseQuoteRsp baseQuote = 1;
inline bool OptionQuoteRsp::has_basequote() const {
  return !_is_default_instance_ && basequote_ != NULL;
}
inline void OptionQuoteRsp::clear_basequote() {
  if (GetArenaNoVirtual() == NULL && basequote_ != NULL) delete basequote_;
  basequote_ = NULL;
}
inline const ::ExchangeQuoteMessage::BaseQuoteRsp& OptionQuoteRsp::basequote() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return basequote_ != NULL ? *basequote_ : *default_instance().basequote_;
#else
  return basequote_ != NULL ? *basequote_ : *default_instance_->basequote_;
#endif
}
inline ::ExchangeQuoteMessage::BaseQuoteRsp* OptionQuoteRsp::mutable_basequote() {
  
  if (basequote_ == NULL) {
    basequote_ = new ::ExchangeQuoteMessage::BaseQuoteRsp;
  }
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
  return basequote_;
}
inline ::ExchangeQuoteMessage::BaseQuoteRsp* OptionQuoteRsp::release_basequote() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
  
  ::ExchangeQuoteMessage::BaseQuoteRsp* temp = basequote_;
  basequote_ = NULL;
  return temp;
}
inline void OptionQuoteRsp::set_allocated_basequote(::ExchangeQuoteMessage::BaseQuoteRsp* basequote) {
  delete basequote_;
  basequote_ = basequote;
  if (basequote) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.baseQuote)
}

// optional bytes strCallOrPutFlag = 2;
inline void OptionQuoteRsp::clear_strcallorputflag() {
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OptionQuoteRsp::strcallorputflag() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  return strcallorputflag_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OptionQuoteRsp::set_strcallorputflag(const ::std::string& value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
inline void OptionQuoteRsp::set_strcallorputflag(const char* value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
inline void OptionQuoteRsp::set_strcallorputflag(const void* value, size_t size) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}
inline ::std::string* OptionQuoteRsp::mutable_strcallorputflag() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  return strcallorputflag_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OptionQuoteRsp::release_strcallorputflag() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
  
  return strcallorputflag_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OptionQuoteRsp::set_allocated_strcallorputflag(::std::string* strcallorputflag) {
  if (strcallorputflag != NULL) {
    
  } else {
    
  }
  strcallorputflag_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcallorputflag);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.strCallOrPutFlag)
}

// optional bytes strStrikePrice = 3;
inline void OptionQuoteRsp::clear_strstrikeprice() {
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OptionQuoteRsp::strstrikeprice() const {
  // @@protoc_insertion_point(field_get:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  return strstrikeprice_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OptionQuoteRsp::set_strstrikeprice(const ::std::string& value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
inline void OptionQuoteRsp::set_strstrikeprice(const char* value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
inline void OptionQuoteRsp::set_strstrikeprice(const void* value, size_t size) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}
inline ::std::string* OptionQuoteRsp::mutable_strstrikeprice() {
  
  // @@protoc_insertion_point(field_mutable:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  return strstrikeprice_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OptionQuoteRsp::release_strstrikeprice() {
  // @@protoc_insertion_point(field_release:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
  
  return strstrikeprice_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OptionQuoteRsp::set_allocated_strstrikeprice(::std::string* strstrikeprice) {
  if (strstrikeprice != NULL) {
    
  } else {
    
  }
  strstrikeprice_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strstrikeprice);
  // @@protoc_insertion_point(field_set_allocated:ExchangeQuoteMessage.OptionQuoteRsp.strStrikePrice)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ExchangeQuoteMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pbExchangeQuoteMessage_2eproto__INCLUDED
