// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbOPKLineMessage.proto

#ifndef PROTOBUF_pbOPKLineMessage_2eproto__INCLUDED
#define PROTOBUF_pbOPKLineMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace OptionKLineMessage {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_pbOPKLineMessage_2eproto();
void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

class OPKLineCacheResponse;
class OPKLineCountRequest;
class OPKLineTimeRequest;
class pbOPKLine;
class pbOptionID;

enum pbOPKLineType {
  M1 = 0,
  M5 = 1,
  DAY = 2,
  pbOPKLineType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  pbOPKLineType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool pbOPKLineType_IsValid(int value);
const pbOPKLineType pbOPKLineType_MIN = M1;
const pbOPKLineType pbOPKLineType_MAX = DAY;
const int pbOPKLineType_ARRAYSIZE = pbOPKLineType_MAX + 1;

// ===================================================================

class pbOptionID : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:OptionKLineMessage.pbOptionID) */ {
 public:
  pbOptionID();
  virtual ~pbOptionID();

  pbOptionID(const pbOptionID& from);

  inline pbOptionID& operator=(const pbOptionID& from) {
    CopyFrom(from);
    return *this;
  }

  static const pbOptionID& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const pbOptionID* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(pbOptionID* other);

  // implements Message ----------------------------------------------

  inline pbOptionID* New() const { return New(NULL); }

  pbOptionID* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const pbOptionID& from);
  void MergeFrom(const pbOptionID& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(pbOptionID* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes strExchange = 1;
  void clear_strexchange();
  static const int kStrExchangeFieldNumber = 1;
  const ::std::string& strexchange() const;
  void set_strexchange(const ::std::string& value);
  void set_strexchange(const char* value);
  void set_strexchange(const void* value, size_t size);
  ::std::string* mutable_strexchange();
  ::std::string* release_strexchange();
  void set_allocated_strexchange(::std::string* strexchange);

  // optional bytes strComodityXYZ = 2;
  void clear_strcomodityxyz();
  static const int kStrComodityXYZFieldNumber = 2;
  const ::std::string& strcomodityxyz() const;
  void set_strcomodityxyz(const ::std::string& value);
  void set_strcomodityxyz(const char* value);
  void set_strcomodityxyz(const void* value, size_t size);
  ::std::string* mutable_strcomodityxyz();
  ::std::string* release_strcomodityxyz();
  void set_allocated_strcomodityxyz(::std::string* strcomodityxyz);

  // optional bytes strContractNo = 3;
  void clear_strcontractno();
  static const int kStrContractNoFieldNumber = 3;
  const ::std::string& strcontractno() const;
  void set_strcontractno(const ::std::string& value);
  void set_strcontractno(const char* value);
  void set_strcontractno(const void* value, size_t size);
  ::std::string* mutable_strcontractno();
  ::std::string* release_strcontractno();
  void set_allocated_strcontractno(::std::string* strcontractno);

  // optional bytes strCallOrPutFlag = 4;
  void clear_strcallorputflag();
  static const int kStrCallOrPutFlagFieldNumber = 4;
  const ::std::string& strcallorputflag() const;
  void set_strcallorputflag(const ::std::string& value);
  void set_strcallorputflag(const char* value);
  void set_strcallorputflag(const void* value, size_t size);
  ::std::string* mutable_strcallorputflag();
  ::std::string* release_strcallorputflag();
  void set_allocated_strcallorputflag(::std::string* strcallorputflag);

  // optional bytes strStrikePrice = 5;
  void clear_strstrikeprice();
  static const int kStrStrikePriceFieldNumber = 5;
  const ::std::string& strstrikeprice() const;
  void set_strstrikeprice(const ::std::string& value);
  void set_strstrikeprice(const char* value);
  void set_strstrikeprice(const void* value, size_t size);
  ::std::string* mutable_strstrikeprice();
  ::std::string* release_strstrikeprice();
  void set_allocated_strstrikeprice(::std::string* strstrikeprice);

  // @@protoc_insertion_point(class_scope:OptionKLineMessage.pbOptionID)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr strexchange_;
  ::google::protobuf::internal::ArenaStringPtr strcomodityxyz_;
  ::google::protobuf::internal::ArenaStringPtr strcontractno_;
  ::google::protobuf::internal::ArenaStringPtr strcallorputflag_;
  ::google::protobuf::internal::ArenaStringPtr strstrikeprice_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
  friend void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

  void InitAsDefaultInstance();
  static pbOptionID* default_instance_;
};
// -------------------------------------------------------------------

class OPKLineCountRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:OptionKLineMessage.OPKLineCountRequest) */ {
 public:
  OPKLineCountRequest();
  virtual ~OPKLineCountRequest();

  OPKLineCountRequest(const OPKLineCountRequest& from);

  inline OPKLineCountRequest& operator=(const OPKLineCountRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const OPKLineCountRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const OPKLineCountRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(OPKLineCountRequest* other);

  // implements Message ----------------------------------------------

  inline OPKLineCountRequest* New() const { return New(NULL); }

  OPKLineCountRequest* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const OPKLineCountRequest& from);
  void MergeFrom(const OPKLineCountRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OPKLineCountRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 iRequestId = 1;
  void clear_irequestid();
  static const int kIRequestIdFieldNumber = 1;
  ::google::protobuf::uint32 irequestid() const;
  void set_irequestid(::google::protobuf::uint32 value);

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  bool has_optionid() const;
  void clear_optionid();
  static const int kOptionIdFieldNumber = 2;
  const ::OptionKLineMessage::pbOptionID& optionid() const;
  ::OptionKLineMessage::pbOptionID* mutable_optionid();
  ::OptionKLineMessage::pbOptionID* release_optionid();
  void set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid);

  // optional uint32 iEndTimeStamp = 3;
  void clear_iendtimestamp();
  static const int kIEndTimeStampFieldNumber = 3;
  ::google::protobuf::uint32 iendtimestamp() const;
  void set_iendtimestamp(::google::protobuf::uint32 value);

  // optional uint32 iCount = 4;
  void clear_icount();
  static const int kICountFieldNumber = 4;
  ::google::protobuf::uint32 icount() const;
  void set_icount(::google::protobuf::uint32 value);

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::OptionKLineMessage::pbOPKLineType type() const;
  void set_type(::OptionKLineMessage::pbOPKLineType value);

  // @@protoc_insertion_point(class_scope:OptionKLineMessage.OPKLineCountRequest)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::OptionKLineMessage::pbOptionID* optionid_;
  ::google::protobuf::uint32 irequestid_;
  ::google::protobuf::uint32 iendtimestamp_;
  ::google::protobuf::uint32 icount_;
  int type_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
  friend void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

  void InitAsDefaultInstance();
  static OPKLineCountRequest* default_instance_;
};
// -------------------------------------------------------------------

class OPKLineTimeRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:OptionKLineMessage.OPKLineTimeRequest) */ {
 public:
  OPKLineTimeRequest();
  virtual ~OPKLineTimeRequest();

  OPKLineTimeRequest(const OPKLineTimeRequest& from);

  inline OPKLineTimeRequest& operator=(const OPKLineTimeRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const OPKLineTimeRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const OPKLineTimeRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(OPKLineTimeRequest* other);

  // implements Message ----------------------------------------------

  inline OPKLineTimeRequest* New() const { return New(NULL); }

  OPKLineTimeRequest* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const OPKLineTimeRequest& from);
  void MergeFrom(const OPKLineTimeRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OPKLineTimeRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 iRequestId = 1;
  void clear_irequestid();
  static const int kIRequestIdFieldNumber = 1;
  ::google::protobuf::uint32 irequestid() const;
  void set_irequestid(::google::protobuf::uint32 value);

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  bool has_optionid() const;
  void clear_optionid();
  static const int kOptionIdFieldNumber = 2;
  const ::OptionKLineMessage::pbOptionID& optionid() const;
  ::OptionKLineMessage::pbOptionID* mutable_optionid();
  ::OptionKLineMessage::pbOptionID* release_optionid();
  void set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid);

  // optional uint32 iStartTimeStamp = 3;
  void clear_istarttimestamp();
  static const int kIStartTimeStampFieldNumber = 3;
  ::google::protobuf::uint32 istarttimestamp() const;
  void set_istarttimestamp(::google::protobuf::uint32 value);

  // optional uint32 iEndTimeStamp = 4;
  void clear_iendtimestamp();
  static const int kIEndTimeStampFieldNumber = 4;
  ::google::protobuf::uint32 iendtimestamp() const;
  void set_iendtimestamp(::google::protobuf::uint32 value);

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::OptionKLineMessage::pbOPKLineType type() const;
  void set_type(::OptionKLineMessage::pbOPKLineType value);

  // @@protoc_insertion_point(class_scope:OptionKLineMessage.OPKLineTimeRequest)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::OptionKLineMessage::pbOptionID* optionid_;
  ::google::protobuf::uint32 irequestid_;
  ::google::protobuf::uint32 istarttimestamp_;
  ::google::protobuf::uint32 iendtimestamp_;
  int type_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
  friend void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

  void InitAsDefaultInstance();
  static OPKLineTimeRequest* default_instance_;
};
// -------------------------------------------------------------------

class pbOPKLine : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:OptionKLineMessage.pbOPKLine) */ {
 public:
  pbOPKLine();
  virtual ~pbOPKLine();

  pbOPKLine(const pbOPKLine& from);

  inline pbOPKLine& operator=(const pbOPKLine& from) {
    CopyFrom(from);
    return *this;
  }

  static const pbOPKLine& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const pbOPKLine* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(pbOPKLine* other);

  // implements Message ----------------------------------------------

  inline pbOPKLine* New() const { return New(NULL); }

  pbOPKLine* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const pbOPKLine& from);
  void MergeFrom(const pbOPKLine& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(pbOPKLine* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 iTradeDate = 1;
  void clear_itradedate();
  static const int kITradeDateFieldNumber = 1;
  ::google::protobuf::uint32 itradedate() const;
  void set_itradedate(::google::protobuf::uint32 value);

  // optional uint32 iTimeStamp = 2;
  void clear_itimestamp();
  static const int kITimeStampFieldNumber = 2;
  ::google::protobuf::uint32 itimestamp() const;
  void set_itimestamp(::google::protobuf::uint32 value);

  // optional double dOpen = 3;
  void clear_dopen();
  static const int kDOpenFieldNumber = 3;
  double dopen() const;
  void set_dopen(double value);

  // optional double dHigh = 4;
  void clear_dhigh();
  static const int kDHighFieldNumber = 4;
  double dhigh() const;
  void set_dhigh(double value);

  // optional double dLow = 5;
  void clear_dlow();
  static const int kDLowFieldNumber = 5;
  double dlow() const;
  void set_dlow(double value);

  // optional double dClose = 6;
  void clear_dclose();
  static const int kDCloseFieldNumber = 6;
  double dclose() const;
  void set_dclose(double value);

  // optional uint64 i64Volume = 7;
  void clear_i64volume();
  static const int kI64VolumeFieldNumber = 7;
  ::google::protobuf::uint64 i64volume() const;
  void set_i64volume(::google::protobuf::uint64 value);

  // optional uint64 i64PositionQty = 8;
  void clear_i64positionqty();
  static const int kI64PositionQtyFieldNumber = 8;
  ::google::protobuf::uint64 i64positionqty() const;
  void set_i64positionqty(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:OptionKLineMessage.pbOPKLine)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::uint32 itradedate_;
  ::google::protobuf::uint32 itimestamp_;
  double dopen_;
  double dhigh_;
  double dlow_;
  double dclose_;
  ::google::protobuf::uint64 i64volume_;
  ::google::protobuf::uint64 i64positionqty_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
  friend void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

  void InitAsDefaultInstance();
  static pbOPKLine* default_instance_;
};
// -------------------------------------------------------------------

class OPKLineCacheResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:OptionKLineMessage.OPKLineCacheResponse) */ {
 public:
  OPKLineCacheResponse();
  virtual ~OPKLineCacheResponse();

  OPKLineCacheResponse(const OPKLineCacheResponse& from);

  inline OPKLineCacheResponse& operator=(const OPKLineCacheResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const OPKLineCacheResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const OPKLineCacheResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(OPKLineCacheResponse* other);

  // implements Message ----------------------------------------------

  inline OPKLineCacheResponse* New() const { return New(NULL); }

  OPKLineCacheResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const OPKLineCacheResponse& from);
  void MergeFrom(const OPKLineCacheResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OPKLineCacheResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 iRequestId = 1;
  void clear_irequestid();
  static const int kIRequestIdFieldNumber = 1;
  ::google::protobuf::uint32 irequestid() const;
  void set_irequestid(::google::protobuf::uint32 value);

  // repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
  int arrklines_size() const;
  void clear_arrklines();
  static const int kArrKLinesFieldNumber = 2;
  const ::OptionKLineMessage::pbOPKLine& arrklines(int index) const;
  ::OptionKLineMessage::pbOPKLine* mutable_arrklines(int index);
  ::OptionKLineMessage::pbOPKLine* add_arrklines();
  ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >*
      mutable_arrklines();
  const ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >&
      arrklines() const;

  // @@protoc_insertion_point(class_scope:OptionKLineMessage.OPKLineCacheResponse)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine > arrklines_;
  ::google::protobuf::uint32 irequestid_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_pbOPKLineMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_pbOPKLineMessage_2eproto();
  friend void protobuf_ShutdownFile_pbOPKLineMessage_2eproto();

  void InitAsDefaultInstance();
  static OPKLineCacheResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// pbOptionID

// optional bytes strExchange = 1;
inline void pbOptionID::clear_strexchange() {
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& pbOptionID::strexchange() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strExchange)
  return strexchange_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_strexchange(const ::std::string& value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strExchange)
}
inline void pbOptionID::set_strexchange(const char* value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strExchange)
}
inline void pbOptionID::set_strexchange(const void* value, size_t size) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strExchange)
}
inline ::std::string* pbOptionID::mutable_strexchange() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strExchange)
  return strexchange_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* pbOptionID::release_strexchange() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strExchange)
  
  return strexchange_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_allocated_strexchange(::std::string* strexchange) {
  if (strexchange != NULL) {
    
  } else {
    
  }
  strexchange_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strexchange);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strExchange)
}

// optional bytes strComodityXYZ = 2;
inline void pbOptionID::clear_strcomodityxyz() {
  strcomodityxyz_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& pbOptionID::strcomodityxyz() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strComodityXYZ)
  return strcomodityxyz_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_strcomodityxyz(const ::std::string& value) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
inline void pbOptionID::set_strcomodityxyz(const char* value) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
inline void pbOptionID::set_strcomodityxyz(const void* value, size_t size) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
inline ::std::string* pbOptionID::mutable_strcomodityxyz() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strComodityXYZ)
  return strcomodityxyz_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* pbOptionID::release_strcomodityxyz() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strComodityXYZ)
  
  return strcomodityxyz_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_allocated_strcomodityxyz(::std::string* strcomodityxyz) {
  if (strcomodityxyz != NULL) {
    
  } else {
    
  }
  strcomodityxyz_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcomodityxyz);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strComodityXYZ)
}

// optional bytes strContractNo = 3;
inline void pbOptionID::clear_strcontractno() {
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& pbOptionID::strcontractno() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strContractNo)
  return strcontractno_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_strcontractno(const ::std::string& value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strContractNo)
}
inline void pbOptionID::set_strcontractno(const char* value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strContractNo)
}
inline void pbOptionID::set_strcontractno(const void* value, size_t size) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strContractNo)
}
inline ::std::string* pbOptionID::mutable_strcontractno() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strContractNo)
  return strcontractno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* pbOptionID::release_strcontractno() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strContractNo)
  
  return strcontractno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_allocated_strcontractno(::std::string* strcontractno) {
  if (strcontractno != NULL) {
    
  } else {
    
  }
  strcontractno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcontractno);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strContractNo)
}

// optional bytes strCallOrPutFlag = 4;
inline void pbOptionID::clear_strcallorputflag() {
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& pbOptionID::strcallorputflag() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  return strcallorputflag_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_strcallorputflag(const ::std::string& value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
inline void pbOptionID::set_strcallorputflag(const char* value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
inline void pbOptionID::set_strcallorputflag(const void* value, size_t size) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
inline ::std::string* pbOptionID::mutable_strcallorputflag() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  return strcallorputflag_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* pbOptionID::release_strcallorputflag() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  
  return strcallorputflag_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_allocated_strcallorputflag(::std::string* strcallorputflag) {
  if (strcallorputflag != NULL) {
    
  } else {
    
  }
  strcallorputflag_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcallorputflag);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}

// optional bytes strStrikePrice = 5;
inline void pbOptionID::clear_strstrikeprice() {
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& pbOptionID::strstrikeprice() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strStrikePrice)
  return strstrikeprice_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_strstrikeprice(const ::std::string& value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strStrikePrice)
}
inline void pbOptionID::set_strstrikeprice(const char* value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strStrikePrice)
}
inline void pbOptionID::set_strstrikeprice(const void* value, size_t size) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strStrikePrice)
}
inline ::std::string* pbOptionID::mutable_strstrikeprice() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strStrikePrice)
  return strstrikeprice_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* pbOptionID::release_strstrikeprice() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strStrikePrice)
  
  return strstrikeprice_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void pbOptionID::set_allocated_strstrikeprice(::std::string* strstrikeprice) {
  if (strstrikeprice != NULL) {
    
  } else {
    
  }
  strstrikeprice_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strstrikeprice);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strStrikePrice)
}

// -------------------------------------------------------------------

// OPKLineCountRequest

// optional uint32 iRequestId = 1;
inline void OPKLineCountRequest::clear_irequestid() {
  irequestid_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineCountRequest::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iRequestId)
  return irequestid_;
}
inline void OPKLineCountRequest::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iRequestId)
}

// optional .OptionKLineMessage.pbOptionID optionId = 2;
inline bool OPKLineCountRequest::has_optionid() const {
  return !_is_default_instance_ && optionid_ != NULL;
}
inline void OPKLineCountRequest::clear_optionid() {
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;
}
inline const ::OptionKLineMessage::pbOptionID& OPKLineCountRequest::optionid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.optionId)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return optionid_ != NULL ? *optionid_ : *default_instance().optionid_;
#else
  return optionid_ != NULL ? *optionid_ : *default_instance_->optionid_;
#endif
}
inline ::OptionKLineMessage::pbOptionID* OPKLineCountRequest::mutable_optionid() {
  
  if (optionid_ == NULL) {
    optionid_ = new ::OptionKLineMessage::pbOptionID;
  }
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineCountRequest.optionId)
  return optionid_;
}
inline ::OptionKLineMessage::pbOptionID* OPKLineCountRequest::release_optionid() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.OPKLineCountRequest.optionId)
  
  ::OptionKLineMessage::pbOptionID* temp = optionid_;
  optionid_ = NULL;
  return temp;
}
inline void OPKLineCountRequest::set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid) {
  delete optionid_;
  optionid_ = optionid;
  if (optionid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.OPKLineCountRequest.optionId)
}

// optional uint32 iEndTimeStamp = 3;
inline void OPKLineCountRequest::clear_iendtimestamp() {
  iendtimestamp_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineCountRequest::iendtimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iEndTimeStamp)
  return iendtimestamp_;
}
inline void OPKLineCountRequest::set_iendtimestamp(::google::protobuf::uint32 value) {
  
  iendtimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iEndTimeStamp)
}

// optional uint32 iCount = 4;
inline void OPKLineCountRequest::clear_icount() {
  icount_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineCountRequest::icount() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iCount)
  return icount_;
}
inline void OPKLineCountRequest::set_icount(::google::protobuf::uint32 value) {
  
  icount_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iCount)
}

// optional .OptionKLineMessage.pbOPKLineType type = 5;
inline void OPKLineCountRequest::clear_type() {
  type_ = 0;
}
inline ::OptionKLineMessage::pbOPKLineType OPKLineCountRequest::type() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.type)
  return static_cast< ::OptionKLineMessage::pbOPKLineType >(type_);
}
inline void OPKLineCountRequest::set_type(::OptionKLineMessage::pbOPKLineType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.type)
}

// -------------------------------------------------------------------

// OPKLineTimeRequest

// optional uint32 iRequestId = 1;
inline void OPKLineTimeRequest::clear_irequestid() {
  irequestid_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineTimeRequest::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iRequestId)
  return irequestid_;
}
inline void OPKLineTimeRequest::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iRequestId)
}

// optional .OptionKLineMessage.pbOptionID optionId = 2;
inline bool OPKLineTimeRequest::has_optionid() const {
  return !_is_default_instance_ && optionid_ != NULL;
}
inline void OPKLineTimeRequest::clear_optionid() {
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;
}
inline const ::OptionKLineMessage::pbOptionID& OPKLineTimeRequest::optionid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.optionId)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return optionid_ != NULL ? *optionid_ : *default_instance().optionid_;
#else
  return optionid_ != NULL ? *optionid_ : *default_instance_->optionid_;
#endif
}
inline ::OptionKLineMessage::pbOptionID* OPKLineTimeRequest::mutable_optionid() {
  
  if (optionid_ == NULL) {
    optionid_ = new ::OptionKLineMessage::pbOptionID;
  }
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineTimeRequest.optionId)
  return optionid_;
}
inline ::OptionKLineMessage::pbOptionID* OPKLineTimeRequest::release_optionid() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.OPKLineTimeRequest.optionId)
  
  ::OptionKLineMessage::pbOptionID* temp = optionid_;
  optionid_ = NULL;
  return temp;
}
inline void OPKLineTimeRequest::set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid) {
  delete optionid_;
  optionid_ = optionid;
  if (optionid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.OPKLineTimeRequest.optionId)
}

// optional uint32 iStartTimeStamp = 3;
inline void OPKLineTimeRequest::clear_istarttimestamp() {
  istarttimestamp_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineTimeRequest::istarttimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iStartTimeStamp)
  return istarttimestamp_;
}
inline void OPKLineTimeRequest::set_istarttimestamp(::google::protobuf::uint32 value) {
  
  istarttimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iStartTimeStamp)
}

// optional uint32 iEndTimeStamp = 4;
inline void OPKLineTimeRequest::clear_iendtimestamp() {
  iendtimestamp_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineTimeRequest::iendtimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iEndTimeStamp)
  return iendtimestamp_;
}
inline void OPKLineTimeRequest::set_iendtimestamp(::google::protobuf::uint32 value) {
  
  iendtimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iEndTimeStamp)
}

// optional .OptionKLineMessage.pbOPKLineType type = 5;
inline void OPKLineTimeRequest::clear_type() {
  type_ = 0;
}
inline ::OptionKLineMessage::pbOPKLineType OPKLineTimeRequest::type() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.type)
  return static_cast< ::OptionKLineMessage::pbOPKLineType >(type_);
}
inline void OPKLineTimeRequest::set_type(::OptionKLineMessage::pbOPKLineType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.type)
}

// -------------------------------------------------------------------

// pbOPKLine

// optional uint32 iTradeDate = 1;
inline void pbOPKLine::clear_itradedate() {
  itradedate_ = 0u;
}
inline ::google::protobuf::uint32 pbOPKLine::itradedate() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.iTradeDate)
  return itradedate_;
}
inline void pbOPKLine::set_itradedate(::google::protobuf::uint32 value) {
  
  itradedate_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.iTradeDate)
}

// optional uint32 iTimeStamp = 2;
inline void pbOPKLine::clear_itimestamp() {
  itimestamp_ = 0u;
}
inline ::google::protobuf::uint32 pbOPKLine::itimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.iTimeStamp)
  return itimestamp_;
}
inline void pbOPKLine::set_itimestamp(::google::protobuf::uint32 value) {
  
  itimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.iTimeStamp)
}

// optional double dOpen = 3;
inline void pbOPKLine::clear_dopen() {
  dopen_ = 0;
}
inline double pbOPKLine::dopen() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dOpen)
  return dopen_;
}
inline void pbOPKLine::set_dopen(double value) {
  
  dopen_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dOpen)
}

// optional double dHigh = 4;
inline void pbOPKLine::clear_dhigh() {
  dhigh_ = 0;
}
inline double pbOPKLine::dhigh() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dHigh)
  return dhigh_;
}
inline void pbOPKLine::set_dhigh(double value) {
  
  dhigh_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dHigh)
}

// optional double dLow = 5;
inline void pbOPKLine::clear_dlow() {
  dlow_ = 0;
}
inline double pbOPKLine::dlow() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dLow)
  return dlow_;
}
inline void pbOPKLine::set_dlow(double value) {
  
  dlow_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dLow)
}

// optional double dClose = 6;
inline void pbOPKLine::clear_dclose() {
  dclose_ = 0;
}
inline double pbOPKLine::dclose() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dClose)
  return dclose_;
}
inline void pbOPKLine::set_dclose(double value) {
  
  dclose_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dClose)
}

// optional uint64 i64Volume = 7;
inline void pbOPKLine::clear_i64volume() {
  i64volume_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 pbOPKLine::i64volume() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.i64Volume)
  return i64volume_;
}
inline void pbOPKLine::set_i64volume(::google::protobuf::uint64 value) {
  
  i64volume_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.i64Volume)
}

// optional uint64 i64PositionQty = 8;
inline void pbOPKLine::clear_i64positionqty() {
  i64positionqty_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 pbOPKLine::i64positionqty() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.i64PositionQty)
  return i64positionqty_;
}
inline void pbOPKLine::set_i64positionqty(::google::protobuf::uint64 value) {
  
  i64positionqty_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.i64PositionQty)
}

// -------------------------------------------------------------------

// OPKLineCacheResponse

// optional uint32 iRequestId = 1;
inline void OPKLineCacheResponse::clear_irequestid() {
  irequestid_ = 0u;
}
inline ::google::protobuf::uint32 OPKLineCacheResponse::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCacheResponse.iRequestId)
  return irequestid_;
}
inline void OPKLineCacheResponse::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCacheResponse.iRequestId)
}

// repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
inline int OPKLineCacheResponse::arrklines_size() const {
  return arrklines_.size();
}
inline void OPKLineCacheResponse::clear_arrklines() {
  arrklines_.Clear();
}
inline const ::OptionKLineMessage::pbOPKLine& OPKLineCacheResponse::arrklines(int index) const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Get(index);
}
inline ::OptionKLineMessage::pbOPKLine* OPKLineCacheResponse::mutable_arrklines(int index) {
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Mutable(index);
}
inline ::OptionKLineMessage::pbOPKLine* OPKLineCacheResponse::add_arrklines() {
  // @@protoc_insertion_point(field_add:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >*
OPKLineCacheResponse::mutable_arrklines() {
  // @@protoc_insertion_point(field_mutable_list:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return &arrklines_;
}
inline const ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >&
OPKLineCacheResponse::arrklines() const {
  // @@protoc_insertion_point(field_list:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace OptionKLineMessage

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OptionKLineMessage::pbOPKLineType> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pbOPKLineMessage_2eproto__INCLUDED
