// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbOPKLineMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pbOPKLineMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace OptionKLineMessage {

void protobuf_ShutdownFile_pbOPKLineMessage_2eproto() {
  delete pbOptionID::default_instance_;
  delete OPKLineCountRequest::default_instance_;
  delete OPKLineTimeRequest::default_instance_;
  delete pbOPKLine::default_instance_;
  delete OPKLineCacheResponse::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_pbOPKLineMessage_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_pbOPKLineMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_pbOPKLineMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  pbOptionID::default_instance_ = new pbOptionID();
  OPKLineCountRequest::default_instance_ = new OPKLineCountRequest();
  OPKLineTimeRequest::default_instance_ = new OPKLineTimeRequest();
  pbOPKLine::default_instance_ = new pbOPKLine();
  OPKLineCacheResponse::default_instance_ = new OPKLineCacheResponse();
  pbOptionID::default_instance_->InitAsDefaultInstance();
  OPKLineCountRequest::default_instance_->InitAsDefaultInstance();
  OPKLineTimeRequest::default_instance_->InitAsDefaultInstance();
  pbOPKLine::default_instance_->InitAsDefaultInstance();
  OPKLineCacheResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pbOPKLineMessage_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_pbOPKLineMessage_2eproto_once_);
void protobuf_AddDesc_pbOPKLineMessage_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_pbOPKLineMessage_2eproto_once_,
                 &protobuf_AddDesc_pbOPKLineMessage_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pbOPKLineMessage_2eproto {
  StaticDescriptorInitializer_pbOPKLineMessage_2eproto() {
    protobuf_AddDesc_pbOPKLineMessage_2eproto();
  }
} static_descriptor_initializer_pbOPKLineMessage_2eproto_;
#endif
bool pbOPKLineType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int pbOptionID::kStrExchangeFieldNumber;
const int pbOptionID::kStrComodityXYZFieldNumber;
const int pbOptionID::kStrContractNoFieldNumber;
const int pbOptionID::kStrCallOrPutFlagFieldNumber;
const int pbOptionID::kStrStrikePriceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

pbOptionID::pbOptionID()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:OptionKLineMessage.pbOptionID)
}

void pbOptionID::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

pbOptionID::pbOptionID(const pbOptionID& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:OptionKLineMessage.pbOptionID)
}

void pbOptionID::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  strexchange_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodityxyz_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcallorputflag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

pbOptionID::~pbOptionID() {
  // @@protoc_insertion_point(destructor:OptionKLineMessage.pbOptionID)
  SharedDtor();
}

void pbOptionID::SharedDtor() {
  strexchange_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodityxyz_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcallorputflag_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void pbOptionID::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const pbOptionID& pbOptionID::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbOPKLineMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbOPKLineMessage_2eproto();
#endif
  return *default_instance_;
}

pbOptionID* pbOptionID::default_instance_ = NULL;

pbOptionID* pbOptionID::New(::google::protobuf::Arena* arena) const {
  pbOptionID* n = new pbOptionID;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void pbOptionID::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionKLineMessage.pbOptionID)
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcomodityxyz_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool pbOptionID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OptionKLineMessage.pbOptionID)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes strExchange = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strexchange()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_strComodityXYZ;
        break;
      }

      // optional bytes strComodityXYZ = 2;
      case 2: {
        if (tag == 18) {
         parse_strComodityXYZ:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcomodityxyz()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_strContractNo;
        break;
      }

      // optional bytes strContractNo = 3;
      case 3: {
        if (tag == 26) {
         parse_strContractNo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcontractno()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_strCallOrPutFlag;
        break;
      }

      // optional bytes strCallOrPutFlag = 4;
      case 4: {
        if (tag == 34) {
         parse_strCallOrPutFlag:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcallorputflag()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_strStrikePrice;
        break;
      }

      // optional bytes strStrikePrice = 5;
      case 5: {
        if (tag == 42) {
         parse_strStrikePrice:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strstrikeprice()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OptionKLineMessage.pbOptionID)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OptionKLineMessage.pbOptionID)
  return false;
#undef DO_
}

void pbOptionID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OptionKLineMessage.pbOptionID)
  // optional bytes strExchange = 1;
  if (this->strexchange().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->strexchange(), output);
  }

  // optional bytes strComodityXYZ = 2;
  if (this->strcomodityxyz().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->strcomodityxyz(), output);
  }

  // optional bytes strContractNo = 3;
  if (this->strcontractno().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->strcontractno(), output);
  }

  // optional bytes strCallOrPutFlag = 4;
  if (this->strcallorputflag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->strcallorputflag(), output);
  }

  // optional bytes strStrikePrice = 5;
  if (this->strstrikeprice().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->strstrikeprice(), output);
  }

  // @@protoc_insertion_point(serialize_end:OptionKLineMessage.pbOptionID)
}

int pbOptionID::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:OptionKLineMessage.pbOptionID)
  int total_size = 0;

  // optional bytes strExchange = 1;
  if (this->strexchange().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strexchange());
  }

  // optional bytes strComodityXYZ = 2;
  if (this->strcomodityxyz().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcomodityxyz());
  }

  // optional bytes strContractNo = 3;
  if (this->strcontractno().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcontractno());
  }

  // optional bytes strCallOrPutFlag = 4;
  if (this->strcallorputflag().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcallorputflag());
  }

  // optional bytes strStrikePrice = 5;
  if (this->strstrikeprice().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strstrikeprice());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pbOptionID::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const pbOptionID*>(&from));
}

void pbOptionID::MergeFrom(const pbOptionID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OptionKLineMessage.pbOptionID)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.strexchange().size() > 0) {

    strexchange_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strexchange_);
  }
  if (from.strcomodityxyz().size() > 0) {

    strcomodityxyz_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcomodityxyz_);
  }
  if (from.strcontractno().size() > 0) {

    strcontractno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcontractno_);
  }
  if (from.strcallorputflag().size() > 0) {

    strcallorputflag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcallorputflag_);
  }
  if (from.strstrikeprice().size() > 0) {

    strstrikeprice_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strstrikeprice_);
  }
}

void pbOptionID::CopyFrom(const pbOptionID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionKLineMessage.pbOptionID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pbOptionID::IsInitialized() const {

  return true;
}

void pbOptionID::Swap(pbOptionID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void pbOptionID::InternalSwap(pbOptionID* other) {
  strexchange_.Swap(&other->strexchange_);
  strcomodityxyz_.Swap(&other->strcomodityxyz_);
  strcontractno_.Swap(&other->strcontractno_);
  strcallorputflag_.Swap(&other->strcallorputflag_);
  strstrikeprice_.Swap(&other->strstrikeprice_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string pbOptionID::GetTypeName() const {
  return "OptionKLineMessage.pbOptionID";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// pbOptionID

// optional bytes strExchange = 1;
void pbOptionID::clear_strexchange() {
  strexchange_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pbOptionID::strexchange() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strExchange)
  return strexchange_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_strexchange(const ::std::string& value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strExchange)
}
 void pbOptionID::set_strexchange(const char* value) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strExchange)
}
 void pbOptionID::set_strexchange(const void* value, size_t size) {
  
  strexchange_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strExchange)
}
 ::std::string* pbOptionID::mutable_strexchange() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strExchange)
  return strexchange_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pbOptionID::release_strexchange() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strExchange)
  
  return strexchange_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_allocated_strexchange(::std::string* strexchange) {
  if (strexchange != NULL) {
    
  } else {
    
  }
  strexchange_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strexchange);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strExchange)
}

// optional bytes strComodityXYZ = 2;
void pbOptionID::clear_strcomodityxyz() {
  strcomodityxyz_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pbOptionID::strcomodityxyz() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strComodityXYZ)
  return strcomodityxyz_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_strcomodityxyz(const ::std::string& value) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
 void pbOptionID::set_strcomodityxyz(const char* value) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
 void pbOptionID::set_strcomodityxyz(const void* value, size_t size) {
  
  strcomodityxyz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strComodityXYZ)
}
 ::std::string* pbOptionID::mutable_strcomodityxyz() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strComodityXYZ)
  return strcomodityxyz_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pbOptionID::release_strcomodityxyz() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strComodityXYZ)
  
  return strcomodityxyz_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_allocated_strcomodityxyz(::std::string* strcomodityxyz) {
  if (strcomodityxyz != NULL) {
    
  } else {
    
  }
  strcomodityxyz_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcomodityxyz);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strComodityXYZ)
}

// optional bytes strContractNo = 3;
void pbOptionID::clear_strcontractno() {
  strcontractno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pbOptionID::strcontractno() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strContractNo)
  return strcontractno_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_strcontractno(const ::std::string& value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strContractNo)
}
 void pbOptionID::set_strcontractno(const char* value) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strContractNo)
}
 void pbOptionID::set_strcontractno(const void* value, size_t size) {
  
  strcontractno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strContractNo)
}
 ::std::string* pbOptionID::mutable_strcontractno() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strContractNo)
  return strcontractno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pbOptionID::release_strcontractno() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strContractNo)
  
  return strcontractno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_allocated_strcontractno(::std::string* strcontractno) {
  if (strcontractno != NULL) {
    
  } else {
    
  }
  strcontractno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcontractno);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strContractNo)
}

// optional bytes strCallOrPutFlag = 4;
void pbOptionID::clear_strcallorputflag() {
  strcallorputflag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pbOptionID::strcallorputflag() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  return strcallorputflag_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_strcallorputflag(const ::std::string& value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
 void pbOptionID::set_strcallorputflag(const char* value) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
 void pbOptionID::set_strcallorputflag(const void* value, size_t size) {
  
  strcallorputflag_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}
 ::std::string* pbOptionID::mutable_strcallorputflag() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  return strcallorputflag_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pbOptionID::release_strcallorputflag() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
  
  return strcallorputflag_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_allocated_strcallorputflag(::std::string* strcallorputflag) {
  if (strcallorputflag != NULL) {
    
  } else {
    
  }
  strcallorputflag_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcallorputflag);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strCallOrPutFlag)
}

// optional bytes strStrikePrice = 5;
void pbOptionID::clear_strstrikeprice() {
  strstrikeprice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pbOptionID::strstrikeprice() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOptionID.strStrikePrice)
  return strstrikeprice_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_strstrikeprice(const ::std::string& value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOptionID.strStrikePrice)
}
 void pbOptionID::set_strstrikeprice(const char* value) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OptionKLineMessage.pbOptionID.strStrikePrice)
}
 void pbOptionID::set_strstrikeprice(const void* value, size_t size) {
  
  strstrikeprice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OptionKLineMessage.pbOptionID.strStrikePrice)
}
 ::std::string* pbOptionID::mutable_strstrikeprice() {
  
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.pbOptionID.strStrikePrice)
  return strstrikeprice_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pbOptionID::release_strstrikeprice() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.pbOptionID.strStrikePrice)
  
  return strstrikeprice_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pbOptionID::set_allocated_strstrikeprice(::std::string* strstrikeprice) {
  if (strstrikeprice != NULL) {
    
  } else {
    
  }
  strstrikeprice_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strstrikeprice);
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.pbOptionID.strStrikePrice)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OPKLineCountRequest::kIRequestIdFieldNumber;
const int OPKLineCountRequest::kOptionIdFieldNumber;
const int OPKLineCountRequest::kIEndTimeStampFieldNumber;
const int OPKLineCountRequest::kICountFieldNumber;
const int OPKLineCountRequest::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OPKLineCountRequest::OPKLineCountRequest()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:OptionKLineMessage.OPKLineCountRequest)
}

void OPKLineCountRequest::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  optionid_ = const_cast< ::OptionKLineMessage::pbOptionID*>(
      ::OptionKLineMessage::pbOptionID::internal_default_instance());
#else
  optionid_ = const_cast< ::OptionKLineMessage::pbOptionID*>(&::OptionKLineMessage::pbOptionID::default_instance());
#endif
}

OPKLineCountRequest::OPKLineCountRequest(const OPKLineCountRequest& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:OptionKLineMessage.OPKLineCountRequest)
}

void OPKLineCountRequest::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  irequestid_ = 0u;
  optionid_ = NULL;
  iendtimestamp_ = 0u;
  icount_ = 0u;
  type_ = 0;
}

OPKLineCountRequest::~OPKLineCountRequest() {
  // @@protoc_insertion_point(destructor:OptionKLineMessage.OPKLineCountRequest)
  SharedDtor();
}

void OPKLineCountRequest::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete optionid_;
  }
}

void OPKLineCountRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const OPKLineCountRequest& OPKLineCountRequest::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbOPKLineMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbOPKLineMessage_2eproto();
#endif
  return *default_instance_;
}

OPKLineCountRequest* OPKLineCountRequest::default_instance_ = NULL;

OPKLineCountRequest* OPKLineCountRequest::New(::google::protobuf::Arena* arena) const {
  OPKLineCountRequest* n = new OPKLineCountRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OPKLineCountRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionKLineMessage.OPKLineCountRequest)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(OPKLineCountRequest, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<OPKLineCountRequest*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(irequestid_, type_);
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool OPKLineCountRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OptionKLineMessage.OPKLineCountRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iRequestId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &irequestid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_optionId;
        break;
      }

      // optional .OptionKLineMessage.pbOptionID optionId = 2;
      case 2: {
        if (tag == 18) {
         parse_optionId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_optionid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_iEndTimeStamp;
        break;
      }

      // optional uint32 iEndTimeStamp = 3;
      case 3: {
        if (tag == 24) {
         parse_iEndTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &iendtimestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_iCount;
        break;
      }

      // optional uint32 iCount = 4;
      case 4: {
        if (tag == 32) {
         parse_iCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &icount_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_type;
        break;
      }

      // optional .OptionKLineMessage.pbOPKLineType type = 5;
      case 5: {
        if (tag == 40) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::OptionKLineMessage::pbOPKLineType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OptionKLineMessage.OPKLineCountRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OptionKLineMessage.OPKLineCountRequest)
  return false;
#undef DO_
}

void OPKLineCountRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OptionKLineMessage.OPKLineCountRequest)
  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->irequestid(), output);
  }

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  if (this->has_optionid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->optionid_, output);
  }

  // optional uint32 iEndTimeStamp = 3;
  if (this->iendtimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->iendtimestamp(), output);
  }

  // optional uint32 iCount = 4;
  if (this->icount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->icount(), output);
  }

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->type(), output);
  }

  // @@protoc_insertion_point(serialize_end:OptionKLineMessage.OPKLineCountRequest)
}

int OPKLineCountRequest::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:OptionKLineMessage.OPKLineCountRequest)
  int total_size = 0;

  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->irequestid());
  }

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  if (this->has_optionid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->optionid_);
  }

  // optional uint32 iEndTimeStamp = 3;
  if (this->iendtimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->iendtimestamp());
  }

  // optional uint32 iCount = 4;
  if (this->icount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->icount());
  }

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPKLineCountRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const OPKLineCountRequest*>(&from));
}

void OPKLineCountRequest::MergeFrom(const OPKLineCountRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OptionKLineMessage.OPKLineCountRequest)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.irequestid() != 0) {
    set_irequestid(from.irequestid());
  }
  if (from.has_optionid()) {
    mutable_optionid()->::OptionKLineMessage::pbOptionID::MergeFrom(from.optionid());
  }
  if (from.iendtimestamp() != 0) {
    set_iendtimestamp(from.iendtimestamp());
  }
  if (from.icount() != 0) {
    set_icount(from.icount());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void OPKLineCountRequest::CopyFrom(const OPKLineCountRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionKLineMessage.OPKLineCountRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPKLineCountRequest::IsInitialized() const {

  return true;
}

void OPKLineCountRequest::Swap(OPKLineCountRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OPKLineCountRequest::InternalSwap(OPKLineCountRequest* other) {
  std::swap(irequestid_, other->irequestid_);
  std::swap(optionid_, other->optionid_);
  std::swap(iendtimestamp_, other->iendtimestamp_);
  std::swap(icount_, other->icount_);
  std::swap(type_, other->type_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string OPKLineCountRequest::GetTypeName() const {
  return "OptionKLineMessage.OPKLineCountRequest";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OPKLineCountRequest

// optional uint32 iRequestId = 1;
void OPKLineCountRequest::clear_irequestid() {
  irequestid_ = 0u;
}
 ::google::protobuf::uint32 OPKLineCountRequest::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iRequestId)
  return irequestid_;
}
 void OPKLineCountRequest::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iRequestId)
}

// optional .OptionKLineMessage.pbOptionID optionId = 2;
bool OPKLineCountRequest::has_optionid() const {
  return !_is_default_instance_ && optionid_ != NULL;
}
void OPKLineCountRequest::clear_optionid() {
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;
}
const ::OptionKLineMessage::pbOptionID& OPKLineCountRequest::optionid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.optionId)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return optionid_ != NULL ? *optionid_ : *default_instance().optionid_;
#else
  return optionid_ != NULL ? *optionid_ : *default_instance_->optionid_;
#endif
}
::OptionKLineMessage::pbOptionID* OPKLineCountRequest::mutable_optionid() {
  
  if (optionid_ == NULL) {
    optionid_ = new ::OptionKLineMessage::pbOptionID;
  }
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineCountRequest.optionId)
  return optionid_;
}
::OptionKLineMessage::pbOptionID* OPKLineCountRequest::release_optionid() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.OPKLineCountRequest.optionId)
  
  ::OptionKLineMessage::pbOptionID* temp = optionid_;
  optionid_ = NULL;
  return temp;
}
void OPKLineCountRequest::set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid) {
  delete optionid_;
  optionid_ = optionid;
  if (optionid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.OPKLineCountRequest.optionId)
}

// optional uint32 iEndTimeStamp = 3;
void OPKLineCountRequest::clear_iendtimestamp() {
  iendtimestamp_ = 0u;
}
 ::google::protobuf::uint32 OPKLineCountRequest::iendtimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iEndTimeStamp)
  return iendtimestamp_;
}
 void OPKLineCountRequest::set_iendtimestamp(::google::protobuf::uint32 value) {
  
  iendtimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iEndTimeStamp)
}

// optional uint32 iCount = 4;
void OPKLineCountRequest::clear_icount() {
  icount_ = 0u;
}
 ::google::protobuf::uint32 OPKLineCountRequest::icount() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.iCount)
  return icount_;
}
 void OPKLineCountRequest::set_icount(::google::protobuf::uint32 value) {
  
  icount_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.iCount)
}

// optional .OptionKLineMessage.pbOPKLineType type = 5;
void OPKLineCountRequest::clear_type() {
  type_ = 0;
}
 ::OptionKLineMessage::pbOPKLineType OPKLineCountRequest::type() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCountRequest.type)
  return static_cast< ::OptionKLineMessage::pbOPKLineType >(type_);
}
 void OPKLineCountRequest::set_type(::OptionKLineMessage::pbOPKLineType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCountRequest.type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OPKLineTimeRequest::kIRequestIdFieldNumber;
const int OPKLineTimeRequest::kOptionIdFieldNumber;
const int OPKLineTimeRequest::kIStartTimeStampFieldNumber;
const int OPKLineTimeRequest::kIEndTimeStampFieldNumber;
const int OPKLineTimeRequest::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OPKLineTimeRequest::OPKLineTimeRequest()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:OptionKLineMessage.OPKLineTimeRequest)
}

void OPKLineTimeRequest::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  optionid_ = const_cast< ::OptionKLineMessage::pbOptionID*>(
      ::OptionKLineMessage::pbOptionID::internal_default_instance());
#else
  optionid_ = const_cast< ::OptionKLineMessage::pbOptionID*>(&::OptionKLineMessage::pbOptionID::default_instance());
#endif
}

OPKLineTimeRequest::OPKLineTimeRequest(const OPKLineTimeRequest& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:OptionKLineMessage.OPKLineTimeRequest)
}

void OPKLineTimeRequest::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  irequestid_ = 0u;
  optionid_ = NULL;
  istarttimestamp_ = 0u;
  iendtimestamp_ = 0u;
  type_ = 0;
}

OPKLineTimeRequest::~OPKLineTimeRequest() {
  // @@protoc_insertion_point(destructor:OptionKLineMessage.OPKLineTimeRequest)
  SharedDtor();
}

void OPKLineTimeRequest::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete optionid_;
  }
}

void OPKLineTimeRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const OPKLineTimeRequest& OPKLineTimeRequest::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbOPKLineMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbOPKLineMessage_2eproto();
#endif
  return *default_instance_;
}

OPKLineTimeRequest* OPKLineTimeRequest::default_instance_ = NULL;

OPKLineTimeRequest* OPKLineTimeRequest::New(::google::protobuf::Arena* arena) const {
  OPKLineTimeRequest* n = new OPKLineTimeRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OPKLineTimeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionKLineMessage.OPKLineTimeRequest)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(OPKLineTimeRequest, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<OPKLineTimeRequest*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(irequestid_, type_);
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool OPKLineTimeRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OptionKLineMessage.OPKLineTimeRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iRequestId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &irequestid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_optionId;
        break;
      }

      // optional .OptionKLineMessage.pbOptionID optionId = 2;
      case 2: {
        if (tag == 18) {
         parse_optionId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_optionid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_iStartTimeStamp;
        break;
      }

      // optional uint32 iStartTimeStamp = 3;
      case 3: {
        if (tag == 24) {
         parse_iStartTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &istarttimestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_iEndTimeStamp;
        break;
      }

      // optional uint32 iEndTimeStamp = 4;
      case 4: {
        if (tag == 32) {
         parse_iEndTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &iendtimestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_type;
        break;
      }

      // optional .OptionKLineMessage.pbOPKLineType type = 5;
      case 5: {
        if (tag == 40) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::OptionKLineMessage::pbOPKLineType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OptionKLineMessage.OPKLineTimeRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OptionKLineMessage.OPKLineTimeRequest)
  return false;
#undef DO_
}

void OPKLineTimeRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OptionKLineMessage.OPKLineTimeRequest)
  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->irequestid(), output);
  }

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  if (this->has_optionid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->optionid_, output);
  }

  // optional uint32 iStartTimeStamp = 3;
  if (this->istarttimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->istarttimestamp(), output);
  }

  // optional uint32 iEndTimeStamp = 4;
  if (this->iendtimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->iendtimestamp(), output);
  }

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->type(), output);
  }

  // @@protoc_insertion_point(serialize_end:OptionKLineMessage.OPKLineTimeRequest)
}

int OPKLineTimeRequest::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:OptionKLineMessage.OPKLineTimeRequest)
  int total_size = 0;

  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->irequestid());
  }

  // optional .OptionKLineMessage.pbOptionID optionId = 2;
  if (this->has_optionid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->optionid_);
  }

  // optional uint32 iStartTimeStamp = 3;
  if (this->istarttimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->istarttimestamp());
  }

  // optional uint32 iEndTimeStamp = 4;
  if (this->iendtimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->iendtimestamp());
  }

  // optional .OptionKLineMessage.pbOPKLineType type = 5;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPKLineTimeRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const OPKLineTimeRequest*>(&from));
}

void OPKLineTimeRequest::MergeFrom(const OPKLineTimeRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OptionKLineMessage.OPKLineTimeRequest)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.irequestid() != 0) {
    set_irequestid(from.irequestid());
  }
  if (from.has_optionid()) {
    mutable_optionid()->::OptionKLineMessage::pbOptionID::MergeFrom(from.optionid());
  }
  if (from.istarttimestamp() != 0) {
    set_istarttimestamp(from.istarttimestamp());
  }
  if (from.iendtimestamp() != 0) {
    set_iendtimestamp(from.iendtimestamp());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void OPKLineTimeRequest::CopyFrom(const OPKLineTimeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionKLineMessage.OPKLineTimeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPKLineTimeRequest::IsInitialized() const {

  return true;
}

void OPKLineTimeRequest::Swap(OPKLineTimeRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OPKLineTimeRequest::InternalSwap(OPKLineTimeRequest* other) {
  std::swap(irequestid_, other->irequestid_);
  std::swap(optionid_, other->optionid_);
  std::swap(istarttimestamp_, other->istarttimestamp_);
  std::swap(iendtimestamp_, other->iendtimestamp_);
  std::swap(type_, other->type_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string OPKLineTimeRequest::GetTypeName() const {
  return "OptionKLineMessage.OPKLineTimeRequest";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OPKLineTimeRequest

// optional uint32 iRequestId = 1;
void OPKLineTimeRequest::clear_irequestid() {
  irequestid_ = 0u;
}
 ::google::protobuf::uint32 OPKLineTimeRequest::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iRequestId)
  return irequestid_;
}
 void OPKLineTimeRequest::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iRequestId)
}

// optional .OptionKLineMessage.pbOptionID optionId = 2;
bool OPKLineTimeRequest::has_optionid() const {
  return !_is_default_instance_ && optionid_ != NULL;
}
void OPKLineTimeRequest::clear_optionid() {
  if (GetArenaNoVirtual() == NULL && optionid_ != NULL) delete optionid_;
  optionid_ = NULL;
}
const ::OptionKLineMessage::pbOptionID& OPKLineTimeRequest::optionid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.optionId)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return optionid_ != NULL ? *optionid_ : *default_instance().optionid_;
#else
  return optionid_ != NULL ? *optionid_ : *default_instance_->optionid_;
#endif
}
::OptionKLineMessage::pbOptionID* OPKLineTimeRequest::mutable_optionid() {
  
  if (optionid_ == NULL) {
    optionid_ = new ::OptionKLineMessage::pbOptionID;
  }
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineTimeRequest.optionId)
  return optionid_;
}
::OptionKLineMessage::pbOptionID* OPKLineTimeRequest::release_optionid() {
  // @@protoc_insertion_point(field_release:OptionKLineMessage.OPKLineTimeRequest.optionId)
  
  ::OptionKLineMessage::pbOptionID* temp = optionid_;
  optionid_ = NULL;
  return temp;
}
void OPKLineTimeRequest::set_allocated_optionid(::OptionKLineMessage::pbOptionID* optionid) {
  delete optionid_;
  optionid_ = optionid;
  if (optionid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:OptionKLineMessage.OPKLineTimeRequest.optionId)
}

// optional uint32 iStartTimeStamp = 3;
void OPKLineTimeRequest::clear_istarttimestamp() {
  istarttimestamp_ = 0u;
}
 ::google::protobuf::uint32 OPKLineTimeRequest::istarttimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iStartTimeStamp)
  return istarttimestamp_;
}
 void OPKLineTimeRequest::set_istarttimestamp(::google::protobuf::uint32 value) {
  
  istarttimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iStartTimeStamp)
}

// optional uint32 iEndTimeStamp = 4;
void OPKLineTimeRequest::clear_iendtimestamp() {
  iendtimestamp_ = 0u;
}
 ::google::protobuf::uint32 OPKLineTimeRequest::iendtimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.iEndTimeStamp)
  return iendtimestamp_;
}
 void OPKLineTimeRequest::set_iendtimestamp(::google::protobuf::uint32 value) {
  
  iendtimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.iEndTimeStamp)
}

// optional .OptionKLineMessage.pbOPKLineType type = 5;
void OPKLineTimeRequest::clear_type() {
  type_ = 0;
}
 ::OptionKLineMessage::pbOPKLineType OPKLineTimeRequest::type() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineTimeRequest.type)
  return static_cast< ::OptionKLineMessage::pbOPKLineType >(type_);
}
 void OPKLineTimeRequest::set_type(::OptionKLineMessage::pbOPKLineType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineTimeRequest.type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int pbOPKLine::kITradeDateFieldNumber;
const int pbOPKLine::kITimeStampFieldNumber;
const int pbOPKLine::kDOpenFieldNumber;
const int pbOPKLine::kDHighFieldNumber;
const int pbOPKLine::kDLowFieldNumber;
const int pbOPKLine::kDCloseFieldNumber;
const int pbOPKLine::kI64VolumeFieldNumber;
const int pbOPKLine::kI64PositionQtyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

pbOPKLine::pbOPKLine()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:OptionKLineMessage.pbOPKLine)
}

void pbOPKLine::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

pbOPKLine::pbOPKLine(const pbOPKLine& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:OptionKLineMessage.pbOPKLine)
}

void pbOPKLine::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  itradedate_ = 0u;
  itimestamp_ = 0u;
  dopen_ = 0;
  dhigh_ = 0;
  dlow_ = 0;
  dclose_ = 0;
  i64volume_ = GOOGLE_ULONGLONG(0);
  i64positionqty_ = GOOGLE_ULONGLONG(0);
}

pbOPKLine::~pbOPKLine() {
  // @@protoc_insertion_point(destructor:OptionKLineMessage.pbOPKLine)
  SharedDtor();
}

void pbOPKLine::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void pbOPKLine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const pbOPKLine& pbOPKLine::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbOPKLineMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbOPKLineMessage_2eproto();
#endif
  return *default_instance_;
}

pbOPKLine* pbOPKLine::default_instance_ = NULL;

pbOPKLine* pbOPKLine::New(::google::protobuf::Arena* arena) const {
  pbOPKLine* n = new pbOPKLine;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void pbOPKLine::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionKLineMessage.pbOPKLine)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(pbOPKLine, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<pbOPKLine*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(itradedate_, i64positionqty_);

#undef ZR_HELPER_
#undef ZR_

}

bool pbOPKLine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OptionKLineMessage.pbOPKLine)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iTradeDate = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &itradedate_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_iTimeStamp;
        break;
      }

      // optional uint32 iTimeStamp = 2;
      case 2: {
        if (tag == 16) {
         parse_iTimeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &itimestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_dOpen;
        break;
      }

      // optional double dOpen = 3;
      case 3: {
        if (tag == 25) {
         parse_dOpen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dopen_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_dHigh;
        break;
      }

      // optional double dHigh = 4;
      case 4: {
        if (tag == 33) {
         parse_dHigh:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dhigh_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_dLow;
        break;
      }

      // optional double dLow = 5;
      case 5: {
        if (tag == 41) {
         parse_dLow:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dlow_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_dClose;
        break;
      }

      // optional double dClose = 6;
      case 6: {
        if (tag == 49) {
         parse_dClose:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dclose_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_i64Volume;
        break;
      }

      // optional uint64 i64Volume = 7;
      case 7: {
        if (tag == 56) {
         parse_i64Volume:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64volume_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_i64PositionQty;
        break;
      }

      // optional uint64 i64PositionQty = 8;
      case 8: {
        if (tag == 64) {
         parse_i64PositionQty:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &i64positionqty_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OptionKLineMessage.pbOPKLine)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OptionKLineMessage.pbOPKLine)
  return false;
#undef DO_
}

void pbOPKLine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OptionKLineMessage.pbOPKLine)
  // optional uint32 iTradeDate = 1;
  if (this->itradedate() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->itradedate(), output);
  }

  // optional uint32 iTimeStamp = 2;
  if (this->itimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->itimestamp(), output);
  }

  // optional double dOpen = 3;
  if (this->dopen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->dopen(), output);
  }

  // optional double dHigh = 4;
  if (this->dhigh() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->dhigh(), output);
  }

  // optional double dLow = 5;
  if (this->dlow() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->dlow(), output);
  }

  // optional double dClose = 6;
  if (this->dclose() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->dclose(), output);
  }

  // optional uint64 i64Volume = 7;
  if (this->i64volume() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(7, this->i64volume(), output);
  }

  // optional uint64 i64PositionQty = 8;
  if (this->i64positionqty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(8, this->i64positionqty(), output);
  }

  // @@protoc_insertion_point(serialize_end:OptionKLineMessage.pbOPKLine)
}

int pbOPKLine::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:OptionKLineMessage.pbOPKLine)
  int total_size = 0;

  // optional uint32 iTradeDate = 1;
  if (this->itradedate() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->itradedate());
  }

  // optional uint32 iTimeStamp = 2;
  if (this->itimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->itimestamp());
  }

  // optional double dOpen = 3;
  if (this->dopen() != 0) {
    total_size += 1 + 8;
  }

  // optional double dHigh = 4;
  if (this->dhigh() != 0) {
    total_size += 1 + 8;
  }

  // optional double dLow = 5;
  if (this->dlow() != 0) {
    total_size += 1 + 8;
  }

  // optional double dClose = 6;
  if (this->dclose() != 0) {
    total_size += 1 + 8;
  }

  // optional uint64 i64Volume = 7;
  if (this->i64volume() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64volume());
  }

  // optional uint64 i64PositionQty = 8;
  if (this->i64positionqty() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->i64positionqty());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pbOPKLine::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const pbOPKLine*>(&from));
}

void pbOPKLine::MergeFrom(const pbOPKLine& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OptionKLineMessage.pbOPKLine)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.itradedate() != 0) {
    set_itradedate(from.itradedate());
  }
  if (from.itimestamp() != 0) {
    set_itimestamp(from.itimestamp());
  }
  if (from.dopen() != 0) {
    set_dopen(from.dopen());
  }
  if (from.dhigh() != 0) {
    set_dhigh(from.dhigh());
  }
  if (from.dlow() != 0) {
    set_dlow(from.dlow());
  }
  if (from.dclose() != 0) {
    set_dclose(from.dclose());
  }
  if (from.i64volume() != 0) {
    set_i64volume(from.i64volume());
  }
  if (from.i64positionqty() != 0) {
    set_i64positionqty(from.i64positionqty());
  }
}

void pbOPKLine::CopyFrom(const pbOPKLine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionKLineMessage.pbOPKLine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pbOPKLine::IsInitialized() const {

  return true;
}

void pbOPKLine::Swap(pbOPKLine* other) {
  if (other == this) return;
  InternalSwap(other);
}
void pbOPKLine::InternalSwap(pbOPKLine* other) {
  std::swap(itradedate_, other->itradedate_);
  std::swap(itimestamp_, other->itimestamp_);
  std::swap(dopen_, other->dopen_);
  std::swap(dhigh_, other->dhigh_);
  std::swap(dlow_, other->dlow_);
  std::swap(dclose_, other->dclose_);
  std::swap(i64volume_, other->i64volume_);
  std::swap(i64positionqty_, other->i64positionqty_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string pbOPKLine::GetTypeName() const {
  return "OptionKLineMessage.pbOPKLine";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// pbOPKLine

// optional uint32 iTradeDate = 1;
void pbOPKLine::clear_itradedate() {
  itradedate_ = 0u;
}
 ::google::protobuf::uint32 pbOPKLine::itradedate() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.iTradeDate)
  return itradedate_;
}
 void pbOPKLine::set_itradedate(::google::protobuf::uint32 value) {
  
  itradedate_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.iTradeDate)
}

// optional uint32 iTimeStamp = 2;
void pbOPKLine::clear_itimestamp() {
  itimestamp_ = 0u;
}
 ::google::protobuf::uint32 pbOPKLine::itimestamp() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.iTimeStamp)
  return itimestamp_;
}
 void pbOPKLine::set_itimestamp(::google::protobuf::uint32 value) {
  
  itimestamp_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.iTimeStamp)
}

// optional double dOpen = 3;
void pbOPKLine::clear_dopen() {
  dopen_ = 0;
}
 double pbOPKLine::dopen() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dOpen)
  return dopen_;
}
 void pbOPKLine::set_dopen(double value) {
  
  dopen_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dOpen)
}

// optional double dHigh = 4;
void pbOPKLine::clear_dhigh() {
  dhigh_ = 0;
}
 double pbOPKLine::dhigh() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dHigh)
  return dhigh_;
}
 void pbOPKLine::set_dhigh(double value) {
  
  dhigh_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dHigh)
}

// optional double dLow = 5;
void pbOPKLine::clear_dlow() {
  dlow_ = 0;
}
 double pbOPKLine::dlow() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dLow)
  return dlow_;
}
 void pbOPKLine::set_dlow(double value) {
  
  dlow_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dLow)
}

// optional double dClose = 6;
void pbOPKLine::clear_dclose() {
  dclose_ = 0;
}
 double pbOPKLine::dclose() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.dClose)
  return dclose_;
}
 void pbOPKLine::set_dclose(double value) {
  
  dclose_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.dClose)
}

// optional uint64 i64Volume = 7;
void pbOPKLine::clear_i64volume() {
  i64volume_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 pbOPKLine::i64volume() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.i64Volume)
  return i64volume_;
}
 void pbOPKLine::set_i64volume(::google::protobuf::uint64 value) {
  
  i64volume_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.i64Volume)
}

// optional uint64 i64PositionQty = 8;
void pbOPKLine::clear_i64positionqty() {
  i64positionqty_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 pbOPKLine::i64positionqty() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.pbOPKLine.i64PositionQty)
  return i64positionqty_;
}
 void pbOPKLine::set_i64positionqty(::google::protobuf::uint64 value) {
  
  i64positionqty_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.pbOPKLine.i64PositionQty)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OPKLineCacheResponse::kIRequestIdFieldNumber;
const int OPKLineCacheResponse::kArrKLinesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OPKLineCacheResponse::OPKLineCacheResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:OptionKLineMessage.OPKLineCacheResponse)
}

void OPKLineCacheResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

OPKLineCacheResponse::OPKLineCacheResponse(const OPKLineCacheResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:OptionKLineMessage.OPKLineCacheResponse)
}

void OPKLineCacheResponse::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  irequestid_ = 0u;
}

OPKLineCacheResponse::~OPKLineCacheResponse() {
  // @@protoc_insertion_point(destructor:OptionKLineMessage.OPKLineCacheResponse)
  SharedDtor();
}

void OPKLineCacheResponse::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void OPKLineCacheResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const OPKLineCacheResponse& OPKLineCacheResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_pbOPKLineMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_pbOPKLineMessage_2eproto();
#endif
  return *default_instance_;
}

OPKLineCacheResponse* OPKLineCacheResponse::default_instance_ = NULL;

OPKLineCacheResponse* OPKLineCacheResponse::New(::google::protobuf::Arena* arena) const {
  OPKLineCacheResponse* n = new OPKLineCacheResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OPKLineCacheResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionKLineMessage.OPKLineCacheResponse)
  irequestid_ = 0u;
  arrklines_.Clear();
}

bool OPKLineCacheResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OptionKLineMessage.OPKLineCacheResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iRequestId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &irequestid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_arrKLines;
        break;
      }

      // repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
      case 2: {
        if (tag == 18) {
         parse_arrKLines:
          DO_(input->IncrementRecursionDepth());
         parse_loop_arrKLines:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_arrklines()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_arrKLines;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OptionKLineMessage.OPKLineCacheResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OptionKLineMessage.OPKLineCacheResponse)
  return false;
#undef DO_
}

void OPKLineCacheResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OptionKLineMessage.OPKLineCacheResponse)
  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->irequestid(), output);
  }

  // repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
  for (unsigned int i = 0, n = this->arrklines_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->arrklines(i), output);
  }

  // @@protoc_insertion_point(serialize_end:OptionKLineMessage.OPKLineCacheResponse)
}

int OPKLineCacheResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:OptionKLineMessage.OPKLineCacheResponse)
  int total_size = 0;

  // optional uint32 iRequestId = 1;
  if (this->irequestid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->irequestid());
  }

  // repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
  total_size += 1 * this->arrklines_size();
  for (int i = 0; i < this->arrklines_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->arrklines(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OPKLineCacheResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const OPKLineCacheResponse*>(&from));
}

void OPKLineCacheResponse::MergeFrom(const OPKLineCacheResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OptionKLineMessage.OPKLineCacheResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  arrklines_.MergeFrom(from.arrklines_);
  if (from.irequestid() != 0) {
    set_irequestid(from.irequestid());
  }
}

void OPKLineCacheResponse::CopyFrom(const OPKLineCacheResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionKLineMessage.OPKLineCacheResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OPKLineCacheResponse::IsInitialized() const {

  return true;
}

void OPKLineCacheResponse::Swap(OPKLineCacheResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OPKLineCacheResponse::InternalSwap(OPKLineCacheResponse* other) {
  std::swap(irequestid_, other->irequestid_);
  arrklines_.UnsafeArenaSwap(&other->arrklines_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string OPKLineCacheResponse::GetTypeName() const {
  return "OptionKLineMessage.OPKLineCacheResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OPKLineCacheResponse

// optional uint32 iRequestId = 1;
void OPKLineCacheResponse::clear_irequestid() {
  irequestid_ = 0u;
}
 ::google::protobuf::uint32 OPKLineCacheResponse::irequestid() const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCacheResponse.iRequestId)
  return irequestid_;
}
 void OPKLineCacheResponse::set_irequestid(::google::protobuf::uint32 value) {
  
  irequestid_ = value;
  // @@protoc_insertion_point(field_set:OptionKLineMessage.OPKLineCacheResponse.iRequestId)
}

// repeated .OptionKLineMessage.pbOPKLine arrKLines = 2;
int OPKLineCacheResponse::arrklines_size() const {
  return arrklines_.size();
}
void OPKLineCacheResponse::clear_arrklines() {
  arrklines_.Clear();
}
const ::OptionKLineMessage::pbOPKLine& OPKLineCacheResponse::arrklines(int index) const {
  // @@protoc_insertion_point(field_get:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Get(index);
}
::OptionKLineMessage::pbOPKLine* OPKLineCacheResponse::mutable_arrklines(int index) {
  // @@protoc_insertion_point(field_mutable:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Mutable(index);
}
::OptionKLineMessage::pbOPKLine* OPKLineCacheResponse::add_arrklines() {
  // @@protoc_insertion_point(field_add:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_.Add();
}
::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >*
OPKLineCacheResponse::mutable_arrklines() {
  // @@protoc_insertion_point(field_mutable_list:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return &arrklines_;
}
const ::google::protobuf::RepeatedPtrField< ::OptionKLineMessage::pbOPKLine >&
OPKLineCacheResponse::arrklines() const {
  // @@protoc_insertion_point(field_list:OptionKLineMessage.OPKLineCacheResponse.arrKLines)
  return arrklines_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace OptionKLineMessage

// @@protoc_insertion_point(global_scope)
