#############################
##     TOP Level PATH      ##
#############################
TO_ROOT = ../..

############################
##     Include Paths      ##
############################
INCLUDES = $(COMMON_INCLUDES) $(3P_INCLUDES)


############################
##    Common Defines      ##
############################
include $(TO_ROOT)/MakeDefines